#include "Emit.h"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <unordered_set>

#include <clang/AST/QualTypeNames.h>

#include "DeclPrinter.h"
#include "Spyll.h"
#include "StringHelper.h"

bool
IsDeclarationPrivate(const clang::NamedDecl* a_decl);

bool
TypeNeedsSmuggling(const clang::Type& a_type);

std::string
GetAccessibleTypeName(const clang::Type& a_type, const clang::ASTContext& a_astContext);

std::string
GetAccessibleTypeName(const clang::QualType& a_type, const clang::ASTContext& a_astContext)
{
	return GetAccessibleTypeName(*a_type, a_astContext);
}

void
EmitHeaderComment(std::string& a_emitString);

void
EmitIncludes(std::string& a_emitString, const Spyll::ReflectionContext& a_context);

void
EmitDependencies(std::string& a_emitString, const std::vector<std::string>& a_dependencies);

void
EmitReflectionRegister(std::string& a_emitString, const Spyll::ReflectionContext& a_context);

void
EmitTypeSmuggleDeclarations(std::string& a_emitString, const Spyll::ReflectionContext& a_context);

std::unordered_set<const clang::Type*> g_typesToSmuggle;

void
EmitMemberStealDeclarations(std::string& a_emitString, const Spyll::ReflectionContext& a_context);

void
RegisterTypes(std::stringstream& a_stream, const Spyll::ReflectionContext& a_context);

void
RegisterVariable(
	std::stringstream& a_stream,
	const clang::VarDecl& a_variable,
	const clang::CXXRecordDecl* a_parent = nullptr
);

void
RegisterField(
	std::stringstream& a_stream,
	const clang::FieldDecl& a_field,
	const clang::CXXRecordDecl& a_parent
);

void
RegisterFunction(
	std::stringstream& a_stream,
	const clang::FunctionDecl& a_function,
	const clang::CXXRecordDecl* a_class = nullptr
);

void
RegisterArgumentForFunction(
	std::stringstream& a_stream,
	const clang::ParmVarDecl& a_parameter
);

void
RegisterEnums(
	std::stringstream& a_stream,
	const Spyll::ReflectionContext& a_context
);

constexpr
static
std::string_view g_emitTemplate = GetTrimmedStringView(R"""(
{HEADER_COMMENT}

#include <Core/Reflection/ReflectionFactory.h>

{REFLECT_INCLUDES}

{REFLECT_SMUGGLE_TYPES}

{REFLECT_STEAL_MEMBERS}

extern "C"
_OYL_EXPORT
void
_ReflectionAssembly_Dependencies(int* a_count, const char*** a_dependencies)
{
	*a_count = {DEPENDENCY_COUNT};

{DEPENDENCIES}
	*a_dependencies = dependencies;
}

extern "C"
_OYL_EXPORT
::Oyl::Reflection::Assembly*
_ReflectionAssembly_Register(::Oyl::Reflection::Internal::ReflectionAllocatorFn a_allocate)
{
	Oyl::Reflection::Internal::AssemblyParams AssemblyParams;
	AssemblyParams.name = "{ASSEMBLY_NAME}";
	Oyl::Reflection::Assembly* AssemblyPtr = Oyl::Reflection::Internal::ReflectionFactory::CreateAssembly(AssemblyParams, a_allocate);

{REFLECTION_REGISTER}

	return AssemblyPtr;
}
)""");

void
EmitCodeFromTool(const Spyll::ReflectionContext& a_context)
{
	std::filesystem::create_directory(".Generated");

	std::ofstream generatedIncludeFile;
	generatedIncludeFile.open(".Generated/Spyll.generated.cpp");

	std::string emitString = std::string(g_emitTemplate);

	EmitReflectionRegister(emitString, a_context);

	EmitHeaderComment(emitString);
	EmitIncludes(emitString, a_context);
	EmitDependencies(emitString, a_context.dependencies);

	EmitMemberStealDeclarations(emitString, a_context);
	EmitTypeSmuggleDeclarations(emitString, a_context);

	FindAndReplace(emitString, "{ASSEMBLY_NAME}", a_context.assemblyName);

	generatedIncludeFile << emitString;
}

void
EmitHeaderComment(std::string& a_emitString)
{
	std::string_view result =
		"// Auto-Generated Source File, Generated by Oyl.Spyll\n"
		"// {GENERATION_DATE}\n"
		"// DO NOT MODIFY!\n";

	FindAndReplace(a_emitString, "{HEADER_COMMENT}", result);
}

void
EmitIncludes(std::string& a_emitString, const Spyll::ReflectionContext& a_context)
{
	std::unordered_set<std::string_view> includeSet;

	for (auto& type : a_context.classes)
	{
		includeSet.insert(a_context.GetSourceManager().getFilename(type.decl->getLocation()));
	}

	for (auto& variable : a_context.globalVariables)
	{
		includeSet.insert(a_context.GetSourceManager().getFilename(variable.decl->getLocation()));
	}

	for (auto& function : a_context.globalFunctions)
	{
		includeSet.insert(a_context.GetSourceManager().getFilename(function.decl->getLocation()));
	}

	for (auto& enum_ : a_context.enums)
	{
		includeSet.insert(a_context.GetSourceManager().getFilename(enum_.decl->getLocation()));
	}

	std::stringstream includes;
	for (const auto& include : includeSet)
	{
		includes << "#include <" << std::filesystem::absolute(include).string() << ">\n";
	}
	FindAndReplace(a_emitString, "{REFLECT_INCLUDES}", includes.str());
}

void
EmitDependencies(std::string& a_emitString, const std::vector<std::string>& a_dependencies)
{
	std::stringstream dependenciesArr;
	if (a_dependencies.empty())
	{
		dependenciesArr << "static const char** dependencies = nullptr";
	} else
	{
		dependenciesArr << "static const char* dependencies[] = { \n";
		for (const auto& dependency : a_dependencies)
		{
			dependenciesArr << "\t\"" << dependency << "\"" << ",\n";
		}
		dependenciesArr << "}";
	}
	dependenciesArr << ";\n";

	AddIndentToStringStream(dependenciesArr);
	FindAndReplace(a_emitString, "{DEPENDENCIES}", dependenciesArr.str());
	FindAndReplace(a_emitString, "{DEPENDENCY_COUNT}", std::to_string(a_dependencies.size()));
}

void
EmitReflectionRegister(std::string& a_emitString, const Spyll::ReflectionContext& a_context)
{
	std::stringstream stream;
	stream.setf(std::ios::boolalpha);

	RegisterTypes(stream, a_context);
	RegisterEnums(stream, a_context);

	// Register type children after all types registered to guarantee calls to Type::Get<T>() succeed
	for (auto& class_ : a_context.classes)
	{
		for (auto* decl : class_.decl->decls())
		{
			switch (decl->getKind())
			{
				case clang::Decl::CXXConstructor:
				{
					break;
				}
				case clang::Decl::CXXDestructor:
				{
					break;
				}
				// Static Member Functions are CXXMethods, but are called like Global Functions
				case clang::Decl::CXXMethod:
				{
					auto* cxxMethodDecl = static_cast<clang::CXXMethodDecl*>(decl);
					RegisterFunction(stream, *cxxMethodDecl, class_.decl);
					break;
				}
				case clang::Decl::Var:
				{
					auto* varDecl = static_cast<clang::VarDecl*>(decl);
					RegisterVariable(stream, *varDecl, class_.decl);
					break;
				}
				case clang::Decl::Field:
				{
					auto* fieldDecl = static_cast<clang::FieldDecl*>(decl);
					RegisterField(stream, *fieldDecl, *class_.decl);
					break;
				}
				default:
				{
					break;
				}
			}
		}
	}

	for (const auto& variable : a_context.globalVariables)
		RegisterVariable(stream, *variable.decl);

	for (const auto& function : a_context.globalFunctions)
		RegisterFunction(stream, *function.decl);

	AddIndentToStringStream(stream);
	FindAndReplace(a_emitString, "{REFLECTION_REGISTER}", stream.str());
}

void
EmitTypeSmuggleDeclarations(std::string& a_emitString, const Spyll::ReflectionContext& a_context)
{
	std::string typeSmuggleString = std::string(
		GetTrimmedStringView(R"""(
namespace
{
	template<typename... Types>
	struct TypeSmuggler
	{
		using tuple_t = std::tuple<Types...>;

		template<size_t Index>
		using element_t = std::tuple_element_t<Index, tuple_t>;

{FRIEND_INJECTIONS}
	};

	template struct TypeSmuggler<
{TYPES_TO_SMUGGLE}
	>;

{SMUGGLE_DECLARATIONS}
}
)"""
		));

	std::stringstream friendInjections;
	std::stringstream typesToSmuggle;
	std::stringstream smuggleDeclarations;

	size_t index = 0;
	for (const auto* type : g_typesToSmuggle)
	{
		if (index > 0)
			typesToSmuggle << ", ";

		auto qualType = clang::QualType(type, 0);
		auto& printingPolicy = a_context.GetASTContext().getPrintingPolicy();
		std::string qualifiedTypeName = clang::TypeName::getFullyQualifiedName(qualType, a_context.GetASTContext(), printingPolicy);
		std::string typeNameAsVar = GetTypeNameAsVar(qualifiedTypeName);

		std::string smugglerFunctionName = "__Smuggler__" + typeNameAsVar;

		std::string friendInjection =
			"friend auto {SMUGGLER_FN}() { return reinterpret_cast<std::add_pointer_t<element_t<{INDEX}>>>(nullptr); };";
		FindAndReplace(friendInjection, "{SMUGGLER_FN}", smugglerFunctionName);
		FindAndReplace(friendInjection, "{INDEX}", std::to_string(index));

		const std::string& typeToSmuggle = qualifiedTypeName;

		std::string smuggleDeclaration =
			"auto {SMUGGLER_FN}(); "
			"using {ACCESSIBLE_NAME} = std::remove_pointer_t<decltype({SMUGGLER_FN}())>;";
		FindAndReplace(smuggleDeclaration, "{SMUGGLER_FN}", smugglerFunctionName);
		FindAndReplace(smuggleDeclaration, "{ACCESSIBLE_NAME}", GetAccessibleTypeName(*type, a_context.GetASTContext()));

		friendInjections << friendInjection << "\n";
		typesToSmuggle << typeToSmuggle << "\n";
		smuggleDeclarations << smuggleDeclaration << "\n";

		index++;
	}

	FindAndReplace(typeSmuggleString, "{FRIEND_INJECTIONS}", friendInjections.str());
	FindAndReplace(typeSmuggleString, "{TYPES_TO_SMUGGLE}", typesToSmuggle.str());
	FindAndReplace(typeSmuggleString, "{SMUGGLE_DECLARATIONS}", smuggleDeclarations.str());

	FindAndReplace(a_emitString, "{REFLECT_SMUGGLE_TYPES}", typeSmuggleString);
}

void
EmitMemberStealDeclarations(std::string& a_emitString, const Spyll::ReflectionContext& a_context)
{
	std::stringstream stream;
	stream.setf(std::ios::boolalpha);

	for (auto& class_ : a_context.classes)
	{
		for (auto* decl : class_.decl->decls())
		{
			if (decl->getKind() < clang::Decl::firstNamed || decl->getKind() > clang::Decl::lastNamed)
				continue;

			clang::NamedDecl* namedDecl = static_cast<clang::NamedDecl*>(decl);

			if (!IsDeclarationPrivate(namedDecl))
				continue;

			std::string typeNameAsVar;
			std::string accessibleTypeName;

			switch (decl->getKind())
			{
				case clang::Decl::Var:
				{
					auto* varDecl = static_cast<clang::VarDecl*>(decl);
					auto varPtrType = decl->getASTContext().getPointerType(varDecl->getType());
					accessibleTypeName = GetAccessibleTypeName(varPtrType, a_context.GetASTContext());
					break;
				}
				case clang::Decl::Field:
				{
					auto* fieldDecl = static_cast<clang::FieldDecl*>(decl);
					auto fieldMemberPtrType = decl->getASTContext().getMemberPointerType(fieldDecl->getType(), class_.decl->getTypeForDecl());
					accessibleTypeName = GetAccessibleTypeName(fieldMemberPtrType, a_context.GetASTContext());
					break;
				}
				case clang::Decl::CXXMethod:
				{
					auto* methodDecl = static_cast<clang::CXXMethodDecl*>(decl);

					// Operators don't have a name, TODO support
					if (!methodDecl->getIdentifier())
						break;

					clang::QualType qualType;
					if (methodDecl->isInstance())
						qualType = methodDecl->getASTContext().getMemberPointerType(methodDecl->getType(), methodDecl->getParent()->getTypeForDecl());
					else
						qualType = methodDecl->getASTContext().getPointerType(methodDecl->getType());
					accessibleTypeName = GetAccessibleTypeName(qualType, methodDecl->getASTContext());
					typeNameAsVar = GetStolenMemberTypeName(*methodDecl);
					break;
				}
				default:
					break;
			}

			if (accessibleTypeName.empty())
				continue;

			if (typeNameAsVar.empty())
				typeNameAsVar = GetStolenMemberTypeName(*namedDecl);

			std::string emitString = std::string(
				GetTrimmedStringView(R"""(
struct {TYPENAME_AS_VAR} { using type = {ACCESSIBLE_TYPE_NAME}; };
template struct Oyl::Reflection::Internal::StealMember<{TYPENAME_AS_VAR}, &{VAR_QUALIFIED_NAME}>;
)"""
				));
			FindAndReplace(emitString, "{TYPENAME_AS_VAR}", typeNameAsVar);
			FindAndReplace(emitString, "{ACCESSIBLE_TYPE_NAME}", accessibleTypeName);
			FindAndReplace(emitString, "{VAR_QUALIFIED_NAME}", namedDecl->getQualifiedNameAsString());

			if (stream.tellp() != 0)
				stream << "\n";
			stream << emitString;
		}
	}

	FindAndReplace(a_emitString, "{REFLECT_STEAL_MEMBERS}", stream.str());
}

static std::unordered_set<const clang::NamedDecl*> g_privateAddressableDeclarations;

bool
IsDeclarationPrivate(const clang::NamedDecl* a_decl)
{
	return a_decl &&
	       (a_decl->getAccess() == clang::AS_protected
	        || a_decl->getAccess() == clang::AS_private);
}

bool
TypeNeedsSmuggling(const clang::Type& a_type)
{
	if (a_type.hasPointerRepresentation())
		return a_type.isNullPtrType()
			       ? false
			       : TypeNeedsSmuggling(*a_type.getPointeeType());

	auto* tagDecl = a_type.getAsTagDecl();
	if (tagDecl && IsDeclarationPrivate(tagDecl))
		return true;

	if (auto* memberPointerType = a_type.getAs<clang::MemberPointerType>())
	{
		if (TypeNeedsSmuggling(*memberPointerType->getClass()))
			return true;

		if (TypeNeedsSmuggling(*memberPointerType->getPointeeType()))
			return true;
	}

	if (auto* functionType = a_type.getAs<clang::FunctionProtoType>())
	{
		if (TypeNeedsSmuggling(*functionType->getReturnType()))
			return true;

		for (const auto& param : functionType->param_types())
		{
			if (TypeNeedsSmuggling(*param))
				return true;
		}
	}

	if (auto* cxxRecordDecl = a_type.getAsCXXRecordDecl())
	{
		if (auto* templateDecl = clang::dyn_cast<clang::ClassTemplateSpecializationDecl>(cxxRecordDecl))
		{
			for (const auto& arg : templateDecl->getTemplateArgs().asArray())
			{
				if (arg.getKind() == clang::TemplateArgument::Type)
				{
					if (TypeNeedsSmuggling(*arg.getAsType()))
						return true;
				}
				if (arg.getKind() == clang::TemplateArgument::Integral)
				{
					if (TypeNeedsSmuggling(*arg.getIntegralType()))
						return true;
				}
			}
		}
	}

	return false;
}

std::string
GetAccessibleTypeName(const clang::Type& a_type, const clang::ASTContext& a_astContext)
{
	// Force an unqualified type
	auto qualType = clang::QualType(&a_type, 0);

	auto& printingPolicy = a_astContext.getPrintingPolicy();
	std::string qualifiedType = clang::TypeName::getFullyQualifiedName(qualType, a_astContext, printingPolicy);
	if (TypeNeedsSmuggling(a_type))
	{
		qualifiedType = GetSmuggledTypeAsTypeName(qualifiedType);
		g_typesToSmuggle.insert(&a_type);
	}

	return qualifiedType;
}

void
RegisterTypes(std::stringstream& a_stream, const Spyll::ReflectionContext& a_context)
{
	for (const auto& type : a_context.classes)
	{
		if (a_stream.tellp() != 0)
		{
			a_stream << "\n";
		}

		std::string typeVar = GetTypeNameAsVar(type.qualifiedName);

		std::string emitString = std::string(
			GetTrimmedStringView(R"""(
Oyl::Reflection::Type* {TYPENAME_AS_VAR}; (void) {TYPENAME_AS_VAR};
{
	Oyl::Reflection::Internal::TypeParams TypeParams;
	TypeParams.assembly = {ASSEMBLY_PTR};
	TypeParams.typeId = Oyl::Reflection::GetTypeId<{ACCESSIBLE_TYPENAME}>();
	TypeParams.qualifiedName = "{QUALIFIED_TYPENAME}";
	TypeParams.name = "{TYPENAME}";
	TypeParams.size = {SIZE};
	TypeParams.alignment = {ALIGNMENT};
	{TYPENAME_AS_VAR} = Oyl::Reflection::Internal::ReflectionFactory::AddTypeToAssembly({ASSEMBLY_PTR}, TypeParams, a_allocate);
}
)"""
			));

		FindAndReplace(emitString, "{ASSEMBLY_PTR}", "AssemblyPtr");
		FindAndReplace(emitString, "{ACCESSIBLE_TYPENAME}", GetAccessibleTypeName(*type.decl->getTypeForDecl(), a_context.GetASTContext()));
		FindAndReplace(emitString, "{QUALIFIED_TYPENAME}", type.qualifiedName);
		FindAndReplace(emitString, "{TYPENAME}", type.qualifiedName);
		FindAndReplace(emitString, "{SIZE}", std::to_string(a_context.GetASTContext().getTypeSizeInChars(type.decl->getTypeForDecl()).getQuantity()));
		FindAndReplace(emitString, "{ALIGNMENT}", std::to_string(a_context.GetASTContext().getPreferredTypeAlignInChars(type.decl->getTypeForDecl()->getCanonicalTypeUnqualified()).getQuantity()));
		FindAndReplace(emitString, "{TYPENAME_AS_VAR}", GetTypeNameAsVar(type.qualifiedName));

		a_stream << emitString;
	}
}

void
RegisterArgumentForFunction(
	std::stringstream& a_stream,
	const clang::ParmVarDecl& a_parameter
)
{
	std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::ArgumentParams Params;
	Params.type = Oyl::Reflection::Type::Get<{TYPE}>();
	Params.name = "{NAME}";
	Oyl::Reflection::Internal::ReflectionFactory::AddArgumentToInvokable(Ptr, Params, a_allocate);
}
)"""
	).data();

	FindAndReplace(emitString, "{TYPE}", GetAccessibleTypeName(a_parameter.getType(), a_parameter.getASTContext()));
	FindAndReplace(emitString, "{NAME}", a_parameter.getName());
	FindAndReplace(emitString, "{PTR}", "Ptr");

	a_stream << emitString;
}

void
RegisterVariable(
	std::stringstream& a_stream,
	const clang::VarDecl& a_variable,
	const clang::CXXRecordDecl* a_parent
)
{
	if (IsDeclarationPrivate(&a_variable))
		g_privateAddressableDeclarations.insert(&a_variable);

	std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::VariableParams Params;
	Params.qualifiedName = "{QUALIFIED_NAME}";
	Params.name = "{NAME}";
	Params.type = Oyl::Reflection::Type::Get<{QUALIFIED_TYPE}>();
	Params.parentType = {PARENT_TYPENAME_AS_VAR};
	Params.accessSpecifier = Oyl::Reflection::AccessSpecifier::{ACCESS_SPECIFIER};
	[[maybe_unused]] auto Ptr = {FACTORY_ADD_CALL};
}
)"""
	).data();

	std::string qualifiedType = GetAccessibleTypeName(a_variable.getType(), a_variable.getASTContext());

	std::string parentTypeNameAsVar = "nullptr";
	std::string factoryAddCall;

	if (a_parent)
	{
		parentTypeNameAsVar = GetTypeNameAsVar(a_parent->getQualifiedNameAsString());
		factoryAddCall = "Oyl::Reflection::Internal::ReflectionFactory::AddVariableToType({PARENT_TYPENAME_AS_VAR}, Params, a_allocate)";
	} else
	{
		factoryAddCall = "Oyl::Reflection::Internal::ReflectionFactory::AddGlobalVariableToAssembly(AssemblyPtr, Params, a_allocate)";
	}

	FindAndReplace(emitString, "{FACTORY_ADD_CALL}", factoryAddCall);

	FindAndReplace(emitString, "{QUALIFIED_NAME}", a_variable.getQualifiedNameAsString());
	FindAndReplace(emitString, "{NAME}", a_variable.getName());
	FindAndReplace(emitString, "{QUALIFIED_TYPE}", qualifiedType);
	FindAndReplace(emitString, "{PARENT_TYPENAME_AS_VAR}", parentTypeNameAsVar);
	FindAndReplace(emitString, "{ACCESS_SPECIFIER}", std::to_string(a_variable.getAccess()));

	// Attributes soon:tm:

	a_stream << emitString;
}

void
RegisterField(
	std::stringstream& a_stream,
	const clang::FieldDecl& a_field,
	const clang::CXXRecordDecl& a_parent
)
{
	if (IsDeclarationPrivate(&a_field))
		g_privateAddressableDeclarations.insert(&a_field);

	std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::FieldParams Params;
	Params.qualifiedName = "{QUALIFIED_NAME}";
	Params.name = "{NAME}";
	Params.type = Oyl::Reflection::Type::Get<{QUALIFIED_TYPE}>();
	Params.parentType = {PARENT_TYPENAME_AS_VAR};
	Params.accessSpecifier = Oyl::Reflection::AccessSpecifier::{ACCESS_SPECIFIER};
	Params.offsetInBits = {OFFSET_IN_BITS};
	Params.isConst = {IS_CONST};
	[[maybe_unused]] auto Ptr = Oyl::Reflection::Internal::ReflectionFactory::AddFieldToType({PARENT_TYPENAME_AS_VAR}, Params, a_allocate);
}
)"""
	).data();

	std::string qualifiedType = GetAccessibleTypeName(a_field.getType(), a_field.getASTContext());

	std::string parentTypeNameAsVar = GetTypeNameAsVar(a_parent.getQualifiedNameAsString());

	FindAndReplace(emitString, "{QUALIFIED_NAME}", a_field.getQualifiedNameAsString());
	FindAndReplace(emitString, "{NAME}", a_field.getName());
	FindAndReplace(emitString, "{QUALIFIED_TYPE}", qualifiedType);
	FindAndReplace(emitString, "{PARENT_TYPENAME_AS_VAR}", parentTypeNameAsVar);
	FindAndReplace(emitString, "{ACCESS_SPECIFIER}", std::to_string(a_field.getAccess()));
	FindAndReplace(emitString, "{OFFSET_IN_BITS}", std::to_string(a_field.getASTContext().getFieldOffset(&a_field)));
	FindAndReplace(emitString, "{IS_CONST}", a_field.getType().isConstQualified() ? "true" : "false");

	// Attributes soon:tm:

	a_stream << emitString;
}

std::string
RegisterFunction_GetRawFunctionString(const clang::FunctionDecl& a_function, const clang::CXXRecordDecl* a_class)
{
	std::string result = GetTrimmedStringView(R"""(
{
	auto address = static_cast<{FN_PTR_SIG}>({RAW_FN_ADDRESS});
	Params.rawFnPtr = *reinterpret_cast<void**>(&address);
}
	)"""
	).data();

	const auto* method = clang::dyn_cast<clang::CXXMethodDecl>(&a_function);
	std::string rawAddress = IsDeclarationPrivate(&a_function)
		                         // (Oyl::Reflection::Internal::StolenMember<__Stolen_Namespace_Function>::value)
		                         ? (method
			                            ? StolenMember(*method)
			                            : StolenMember(a_function))
								 // Namespace::Function
		                         : "&" + a_function.getQualifiedNameAsString();
	FindAndReplace(result, "{RAW_FN_ADDRESS}", rawAddress);

	clang::QualType fnPtrSignature = method && method->isInstance()
		                                 ? method->getASTContext().getMemberPointerType(method->getType(), a_class->getTypeForDecl())
		                                 : a_function.getASTContext().getPointerType(a_function.getType());
	FindAndReplace(result, "{FN_PTR_SIG}", GetAccessibleTypeName(fnPtrSignature, a_function.getASTContext()));

	return result;
}

std::string
RegisterFunction_GetTypesafeFunctionString(const clang::FunctionDecl& a_function, const clang::CXXRecordDecl* a_class)
{
	std::string result = GetTrimmedStringView(R"""(
{
	auto thunkLambda = []({TYPESAFE_NAME_SIGNATURE}) -> std::any
	{
{TYPESAFE_ANY_CALL}
	};
	std::any(*thunkFnPtr)({TYPESAFE_TYPE_SIGNATURE}) = thunkLambda;
	Params.typeSafeThunkFnPtr = reinterpret_cast<void*>(thunkFnPtr);
}
)"""
	).data();

	const auto* method = clang::dyn_cast<clang::CXXMethodDecl>(&a_function);

	std::string_view std_any_ref = "std::any&";

	// Function arguments signature with names
	// (std::any& arg1, std::any& arg2, ...)
	std::string nameSignature;
	for (const auto* parameter : a_function.parameters())
	{
		if (!nameSignature.empty())
			nameSignature += ", ";

		nameSignature += std_any_ref;
		nameSignature += " ";
		nameSignature += parameter->getName();
	}
	if (method && method->isInstance())
	{
		if (nameSignature.empty())
			nameSignature = "std::any& __a_self";
		else
			nameSignature = "std::any& __a_self" ", " + nameSignature;
	}
	FindAndReplace(result, "{TYPESAFE_NAME_SIGNATURE}", nameSignature);

	// Function arguments signature without names
	// (std::any&, std::any&, ...)
	std::string typeSignature;
	for (auto _ : a_function.parameters())
	{
		(void) _;
		if (!typeSignature.empty())
			typeSignature += ", ";

		typeSignature += std_any_ref;
	}
	if (method && method->isInstance())
	{
		if (typeSignature.empty())
			typeSignature = "std::any&";
		else
			typeSignature = "std::any&" ", " + typeSignature;
	}
	FindAndReplace(result, "{TYPESAFE_TYPE_SIGNATURE}", typeSignature);

	std::stringstream callStatement;
	{
		std::string callFunc = "({SELF}{FN_PTR_DEREFERENCE}{FN_NAME})";

		std::string functionName = IsDeclarationPrivate(&a_function)
			                           // *(Oyl::Reflection::Internal::StolenMember<__Stolen_Namespace_Function>::value)
			                           ? method
				                             ? StolenMember(*method)
				                             : StolenMember(a_function)
			                           // Namespace::Function
			                           : a_function.getQualifiedNameAsString();

		std::string self;
		std::string fnPtrDereference;
		if (method && method->isInstance())
		{
			self = "__self->";
			if (IsDeclarationPrivate(&a_function))
				fnPtrDereference = "*";
		}

		FindAndReplace(callFunc, "{SELF}", self);
		FindAndReplace(callFunc, "{FN_PTR_DEREFERENCE}", fnPtrDereference);
		FindAndReplace(callFunc, "{FN_NAME}", functionName);

		callStatement << callFunc;
	}
	callStatement << "(";
	std::string callStatementArgs;
	for (const auto* parameter : a_function.parameters())
	{
		if (!callStatementArgs.empty())
			callStatementArgs += ", ";

		callStatementArgs += "\n";
		std::string declaration = "std::any_cast<{TYPE}>({NAME})";
		std::string type = GetAccessibleTypeName(parameter->getOriginalType(), parameter->getASTContext());
		if (parameter->getOriginalType()->isRValueReferenceType())
		{
			type = "std::remove_reference_t<" + type + ">&";
			declaration = "std::move(" + declaration + ")";
		}
		FindAndReplace(declaration, "{TYPE}", type);
		FindAndReplace(declaration, "{NAME}", parameter->getName());

		callStatementArgs += "\t" + declaration;
	}
	callStatement << callStatementArgs;
	callStatement << ")";

	std::stringstream callReturn;
	if (method && method->isInstance())
		callReturn << "auto __self = std::any_cast<" << a_class->getQualifiedNameAsString() << "*>(__a_self);\n";
	if (a_function.getReturnType() == a_function.getASTContext().VoidTy)
	{
		callReturn << callStatement.str() << ";\n";
		callReturn << "return std::any {};";
	} else
	{
		callReturn << "std::any result = " << callStatement.str() << ";\n";
		callReturn << "return result;";
	}
	AddIndentToStringStream(callReturn, "\t\t");
	FindAndReplace(result, "{TYPESAFE_ANY_CALL}", callReturn.str());

	return result;
}

void
RegisterFunction(
	std::stringstream& a_stream,
	const clang::FunctionDecl& a_function,
	const clang::CXXRecordDecl* a_class
)
{
	// Operator, No operator support yet
	if (!a_function.getIdentifier())
		return;

	if (IsDeclarationPrivate(&a_function))
		g_privateAddressableDeclarations.insert(&a_function);

	std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::{FUNC_KIND}Params Params;
	Params.qualifiedName = "{QUALIFIED_NAME}";
	Params.name = "{NAME}";
	Params.returnType = Oyl::Reflection::Type::Get<{RETURN_TYPE}>();
	Params.parentType = {PARENT_TYPENAME_AS_VAR};
	Params.accessSpecifier = Oyl::Reflection::AccessSpecifier::{ACCESS_SPECIFIER};
{METHOD_PARAMS}
{RAW_FN_PTR}
{TYPESAFE_FN_PTR}
	[[maybe_unused]] auto Ptr = Oyl::Reflection::Internal::ReflectionFactory::Add{FUNC_KIND}ToType({PARENT_TYPENAME_AS_VAR}, Params, a_allocate);
{ARGUMENTS}
}
)"""
	).data();

	std::string qualifiedReturnType = GetAccessibleTypeName(a_function.getReturnType(), a_function.getASTContext());

	std::string funcKind = "Function";
	std::string methodParams;
	std::string parentTypeNameAsVar = "nullptr";
	std::string factoryAddCall;

	if (a_class)
	{
		parentTypeNameAsVar = GetTypeNameAsVar(a_class->getQualifiedNameAsString());
		factoryAddCall = "Oyl::Reflection::Internal::ReflectionFactory::Add{FUNC_KIND}ToType({PARENT_TYPENAME_AS_VAR}, Params, a_allocate)";
	} else
	{
		factoryAddCall = "Oyl::Reflection::Internal::ReflectionFactory::AddGlobalFunctionToAssembly(AssemblyPtr, Params, a_allocate)";
	}

	const auto* method = clang::dyn_cast<clang::CXXMethodDecl>(&a_function);
	if (method && method->isInstance())
	{
		funcKind = "Method";
		std::stringstream s;
		s << "\tParams.isConst = " << (method->isConst() ? "true" : "false") << ";\n";
		s << "\tParams.isVirtual = " << (method->isVirtual() ? "true" : "false") << ";";
		methodParams = s.str();
	}

	std::string rawFnPtrString;
	std::string typesafeFnPtrString;
	if (!a_function.isDeleted() && !a_function.isPureVirtual())
	{
		rawFnPtrString = RegisterFunction_GetRawFunctionString(a_function, a_class);
		typesafeFnPtrString = RegisterFunction_GetTypesafeFunctionString(a_function, a_class);
	}

	FindAndReplace(emitString, "{RAW_FN_PTR}", rawFnPtrString);
	FindAndReplace(emitString, "{TYPESAFE_FN_PTR}", typesafeFnPtrString);

	FindAndReplace(emitString, "{FACTORY_ADD_CALL}", factoryAddCall);

	FindAndReplace(emitString, "{FUNC_KIND}", funcKind);
	FindAndReplace(emitString, "{QUALIFIED_NAME}", a_function.getQualifiedNameAsString());
	FindAndReplace(emitString, "{NAME}", a_function.getName());
	FindAndReplace(emitString, "{RETURN_TYPE}", qualifiedReturnType);
	FindAndReplace(emitString, "{PARENT_TYPENAME_AS_VAR}", parentTypeNameAsVar);
	FindAndReplace(emitString, "{ACCESS_SPECIFIER}", std::to_string(a_function.getAccess()));
	FindAndReplace(emitString, "{METHOD_PARAMS}", methodParams);

	std::stringstream argumentsStream;
	for (const auto* parameter : a_function.parameters())
		RegisterArgumentForFunction(argumentsStream, *parameter);
	AddIndentToStringStream(argumentsStream);
	FindAndReplace(emitString, "{ARGUMENTS}", argumentsStream.str());

	// Attributes

	a_stream << emitString;
}

void
RegisterEnums(std::stringstream& a_stream, const Spyll::ReflectionContext& a_context)
{
	for (const auto& enum_ : a_context.enums)
	{
		std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::EnumParams EnumParams;
	EnumParams.qualifiedName = "{QUALIFIED_NAME}";
	EnumParams.name = "{NAME}";
	EnumParams.underlyingType = Oyl::Reflection::Type::Get<{UNDERLYING_TYPE}>();
	EnumParams.nValues = static_cast<size_t>({SIZE});
	[[maybe_unused]] auto Ptr = Oyl::Reflection::Internal::ReflectionFactory::AddEnumToAssembly(AssemblyPtr, EnumParams, a_allocate);
{ENTRIES}
}
)"""
		).data();

		FindAndReplace(emitString, "{QUALIFIED_NAME}", enum_.qualifiedName);
		FindAndReplace(emitString, "{NAME}", enum_.name);

		size_t nEnumerators = 0;
		std::stringstream entryStream;
		for (auto* entry : enum_.decl->enumerators())
		{
			nEnumerators++;
			std::string entryString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::EnumValueParams EnumValueParams;
	EnumValueParams.identifier = "{IDENTIFIER}";
	EnumValueParams.value = static_cast<decltype(EnumValueParams.value)>({VALUE});
	Oyl::Reflection::Internal::ReflectionFactory::AddValueToEnum(Ptr, EnumValueParams, a_allocate);
}
)"""
			).data();

			FindAndReplace(entryString, "{IDENTIFIER}", entry->getName());
			FindAndReplace(entryString, "{VALUE}", std::to_string(entry->getInitVal().getExtValue()));

			entryStream << entryString;
		}
		AddIndentToStringStream(entryStream);
		FindAndReplace(emitString, "{ENTRIES}", entryStream.str());

		FindAndReplace(emitString, "{UNDERLYING_TYPE}", GetAccessibleTypeName(enum_.decl->getIntegerType(), a_context.GetASTContext()));
		FindAndReplace(emitString, "{SIZE}", std::to_string(nEnumerators));

		a_stream << emitString;
	}
}
