#include "Emit.h"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <unordered_set>

#include <Spyll/Tool/Core/ReflectionParser.h>

#include "DeclPrinter.h"
#include "SpyllTool.h"
#include "StringHelper.h"

std::string
GetAccessibleTypeName(const Spyll::Type* a_type, std::string_view a_typeAsString);

void
EmitHeaderComment(std::string& a_emitString);

void
EmitIncludes(std::string& a_emitString, const Spyll::ReflectionParser* a_parser);

void
EmitDependencies(std::string& a_emitString, const std::vector<std::string_view>& a_tool);

void
EmitReflectionRegister(std::string& a_emitString, const Spyll::ReflectionParser* a_parser);

void
EmitTypeSmuggleDeclarations(std::string& a_emitString, const Spyll::ReflectionParser* a_parser);

void
EmitMemberStealDeclarations(std::string& a_emitString, const Spyll::ReflectionParser* a_parser);

void
RegisterTypes(std::stringstream& a_stream, const Spyll::ReflectionParser* a_parser);

void
RegisterVariable(
	std::stringstream& a_stream,
	const Spyll::Variable& a_variable,
	const Spyll::Class* a_parent = nullptr
);

void
RegisterField(
	std::stringstream& a_stream,
	const Spyll::Field& a_field,
	const Spyll::Class* a_parent = nullptr
);

void
RegisterFunction(
	std::stringstream& a_stream,
	const Spyll::Function& a_variable,
	const Spyll::Class* a_class = nullptr
);

void
RegisterVariablesForType(
	std::stringstream& a_stream,
	const Spyll::Class& a_parentType
);

void
RegisterFieldsForType(
	std::stringstream& a_stream,
	const Spyll::Record& a_parentType
);

void
RegisterFunctionsForType(
	std::stringstream& a_stream,
	const Spyll::Class& a_parentType
);

void
RegisterMethodsForType(
	std::stringstream& a_stream,
	const Spyll::Class& a_class
);

void
RegisterArgumentForFunction(
	std::stringstream& a_stream,
	const Spyll::Argument& a_argument
);

void
RegisterGlobalVariables(
	std::stringstream& a_stream,
	const Spyll::ReflectionParser* a_parser
);

void
RegisterGlobalFunctions(
	std::stringstream& a_stream,
	const Spyll::ReflectionParser* a_parser
);

void
RegisterEnums(
	std::stringstream& a_stream,
	const Spyll::ReflectionParser* a_parser
);

constexpr
static
std::string_view g_emitTemplate = GetTrimmedStringView(R"""(
{HEADER_COMMENT}

#include <Core/Reflection/ReflectionFactory.h>

{REFLECT_INCLUDES}

{REFLECT_SMUGGLE_TYPES}

{REFLECT_STEAL_MEMBERS}

extern "C"
_OYL_EXPORT
void
_ReflectionAssembly_Dependencies(int* a_count, const char*** a_dependencies)
{
	*a_count = {DEPENDENCY_COUNT};

{DEPENDENCIES}
	*a_dependencies = dependencies;
}

extern "C"
_OYL_EXPORT
::Oyl::Reflection::Assembly*
_ReflectionAssembly_Register(::Oyl::Reflection::Internal::ReflectionAllocatorFn a_allocate)
{
	Oyl::Reflection::Internal::AssemblyParams AssemblyParams;
	AssemblyParams.name = "{ASSEMBLY_NAME}";
	Oyl::Reflection::Assembly* AssemblyPtr = Oyl::Reflection::Internal::ReflectionFactory::CreateAssembly(AssemblyParams, a_allocate);

{REFLECTION_REGISTER}

	return AssemblyPtr;
}
)""");

void
EmitCodeFromTool(const Spyll::ReflectionParser* a_parser)
{
	std::filesystem::create_directory(".Generated");

	std::ofstream generatedIncludeFile;
	generatedIncludeFile.open(".Generated/Spyll.generated.cpp");

	std::string emitString = std::string(g_emitTemplate);

	EmitReflectionRegister(emitString, a_parser);

	EmitHeaderComment(emitString);
	EmitIncludes(emitString, a_parser);
	EmitDependencies(emitString, g_tool.dependencies);
	EmitMemberStealDeclarations(emitString, a_parser);

	FindAndReplace(emitString, "{ASSEMBLY_NAME}", g_tool.assemblyName);

	generatedIncludeFile << emitString;
}

void
EmitHeaderComment(std::string& a_emitString)
{
	std::string_view result =
		"// Auto-Generated Source File, Generated by Oyl.Spyll\n"
		"// {GENERATION_DATE}\n"
		"// DO NOT MODIFY!\n";

	FindAndReplace(a_emitString, "{HEADER_COMMENT}", result);
}

void
EmitIncludes(std::string& a_emitString, const Spyll::ReflectionParser* a_parser)
{
	std::unordered_set<std::string_view> includeSet;

	for (const Spyll::Type* type : a_parser->GetTypes())
	{
		includeSet.insert(type->GetSourceFile());
	}

	for (const Spyll::Variable& variable : a_parser->GetGlobalVariables())
	{
		includeSet.insert(variable.GetSourceFile());
	}

	for (const Spyll::Function& function : a_parser->GetGlobalFunctions())
	{
		includeSet.insert(function.GetSourceFile());
	}

	for (const Spyll::Enum& enum_ : a_parser->GetEnums())
	{
		includeSet.insert(enum_.GetSourceFile());
	}

	std::stringstream includes;
	for (const auto& include : includeSet)
	{
		includes << "#include <" << include << ">\n";
	}
	FindAndReplace(a_emitString, "{REFLECT_INCLUDES}", includes.str());
}

void
EmitDependencies(std::string& a_emitString, const std::vector<std::string_view>& a_dependencies)
{
	std::stringstream dependenciesArr;
	if (a_dependencies.empty())
	{
		dependenciesArr << "static const char** dependencies = nullptr";
	} else
	{
		dependenciesArr << "static const char* dependencies[] = { \n";
		for (const auto& dependency : a_dependencies)
		{
			dependenciesArr << "\t\"" << dependency << "\"" << ",\n";
		}
		dependenciesArr << "}";
	}
	dependenciesArr << ";\n";

	AddIndentToStringStream(dependenciesArr);
	FindAndReplace(a_emitString, "{DEPENDENCIES}", dependenciesArr.str());
	FindAndReplace(a_emitString, "{DEPENDENCY_COUNT}", std::to_string(a_dependencies.size()));
}

void
EmitReflectionRegister(std::string& a_emitString, const Spyll::ReflectionParser* a_parser)
{
	std::stringstream stream;
	stream.setf(std::ios::boolalpha);

	RegisterTypes(stream, a_parser);
	RegisterEnums(stream, a_parser);

	// Register type children after all types registered to guarantee calls to Type::Get<T>() succeed
	for (const auto& class_ : a_parser->GetClasses())
	{
		for (const auto& field : class_.GetFields())
		{
			RegisterField(stream, field, &class_);
		}
		for (const auto& method : class_.GetMethods())
		{
			RegisterFunction(stream, method, &class_);
		}
		for (const auto& variable : class_.GetVariables())
		{
			RegisterVariable(stream, variable, &class_);
		}
		for (const auto& function : class_.GetFunctions())
		{
			RegisterFunction(stream, function, &class_);
		}

		//RegisterVariablesForType(stream, class_);
		//RegisterFieldsForType(stream, class_);
		//RegisterFunctionsForType(stream, class_);
		//RegisterMethodsForType(stream, class_);
	}

	for (const auto& variable : a_parser->GetGlobalVariables())
		RegisterVariable(stream, variable);

	for (const auto& function : a_parser->GetGlobalFunctions())
		RegisterFunction(stream, function);

	//RegisterGlobalVariables(stream, a_parser);
	//RegisterGlobalFunctions(stream, a_parser);

	AddIndentToStringStream(stream);
	FindAndReplace(a_emitString, "{REFLECTION_REGISTER}", stream.str());
}

std::unordered_set<std::string_view> g_typesToSmuggle;

void
EmitTypeSmuggleDeclarations(std::string& a_emitString, const Spyll::ReflectionParser* a_parser)
{
	std::stringstream stream;
	stream.setf(std::ios::boolalpha);

	std::string emitString = std::string(
		GetTrimmedStringView(R"""(
namespace
{
	template<typename... Types>
	struct TypeSmuggler
	{
		using tuple_t = std::tuple<Types...>;

		template<size_t Index>
		using element_t = std::tuple_element_t<Index, tuple_t>;

{FRIEND_INJECTIONS}

		friend auto __Smuggler__Oyl_CommandLine_Impl() { return reinterpret_cast<std::add_pointer_t<element_t<0>>>(nullptr); };
		friend auto __Smuggler__Oyl_EventDispatcher_ListenerList() { return reinterpret_cast<std::add_pointer_t<element_t<1>>>(nullptr); };
		friend auto __Smuggler__Oyl_EventDispatcher_ListenerDescriptor() { return reinterpret_cast<std::add_pointer_t<element_t<2>>>(nullptr); };
		friend auto __Smuggler__Oyl_Internal_ResourceHandleBase_Tag() { return reinterpret_cast<std::add_pointer_t<element_t<3>>>(nullptr); };
	};

	template struct TypeSmuggler<
{TYPES_TO_SMUGGLE}
		Oyl::CommandLine::Impl,
		Oyl::EventDispatcher::ListenerList,
		Oyl::EventDispatcher::ListenerDescriptor,
		Oyl::Internal::ResourceHandleBase::Tag
	>;

{SMUGGLE_DECLARATIONS}

	auto __Smuggler__Oyl_CommandLine_Impl();
	using __Smuggled__Oyl_CommandLine_Impl = std::remove_pointer_t<decltype(__Smuggler__Oyl_CommandLine_Impl())>;
	auto __Smuggler__Oyl_EventDispatcher_ListenerList();
	using __Smuggled__Oyl_EventDispatcher_ListenerList = std::remove_pointer_t<decltype(__Smuggler__Oyl_EventDispatcher_ListenerList())>;
	auto __Smuggler__Oyl_EventDispatcher_ListenerDescriptor();
	using __Smuggled__Oyl_EventDispatcher_ListenerDescriptor = std::remove_pointer_t<decltype(__Smuggler__Oyl_EventDispatcher_ListenerDescriptor())>;
	auto __Smuggler__Oyl_Internal_ResourceHandleBase_Tag();
	using __Smuggled__Oyl_Internal_ResourceHandleBase_Tag = std::remove_pointer_t<decltype(__Smuggler__Oyl_Internal_ResourceHandleBase_Tag())>;
}
)"""
		));

	std::stringstream friendInjections;
	std::stringstream typesToSmuggle;
	std::stringstream smuggleDeclarations;

	for (const auto* type : a_parser->GetTypes())
	{
		// We only need to smuggle non-publicly accessible types
		if (type->GetAccessSpecifier() == Spyll::AccessSpecifier::Public
		    || type->GetAccessSpecifier() == Spyll::AccessSpecifier::None)
		{
			continue;
		}

		FindAndReplace(emitString, "{ASSEMBLY_PTR}", "AssemblyPtr");
		FindAndReplace(emitString, "{QUALIFIED_TYPENAME}", type->GetQualifiedName());
		FindAndReplace(emitString, "{TYPENAME}", type->GetName());
		FindAndReplace(emitString, "{SIZE}", std::to_string(type->GetSize()));
		FindAndReplace(emitString, "{ALIGNMENT}", std::to_string(type->GetAlignment()));
		FindAndReplace(emitString, "{TYPENAME_AS_VAR}", GetTypeNameAsVar(type->GetQualifiedName()));

		stream << emitString;
	}

	FindAndReplace(a_emitString, "{REFLECT_SMUGGLE_TYPES}", stream.str());
}

void
EmitMemberStealDeclarations(std::string& a_emitString, const Spyll::ReflectionParser* a_parser)
{
	std::stringstream stream;
	stream.setf(std::ios::boolalpha);

	auto isPublic = [](Spyll::AccessSpecifier a_accessSpec)
	{
		return a_accessSpec == Spyll::AccessSpecifier::Public;
	};

	for (const auto& class_ : a_parser->GetClasses())
	{
		for (const auto& variable : class_.GetVariables())
		{
			if (!variable.ShouldReflect() || isPublic(variable.GetAccessSpecifier()))
				continue;

			auto typeNameAsVar = GetStolenMemberTypeName(variable);

			stream << "struct " << typeNameAsVar << " { using type = ";
			stream << GetAccessibleTypeName(variable.GetType(), variable.GetTypeAsString()) << "*; };\n";
			stream << "template struct Oyl::Reflection::Internal::StealMember<" << typeNameAsVar << ", &" << variable.GetQualifiedName() << ">;\n";
		}

		for (const auto& field : class_.GetFields())
		{
			if (!field.ShouldReflect() || isPublic(field.GetAccessSpecifier()))
				continue;

			auto typeNameAsVar = GetStolenMemberTypeName(field);

			stream << "struct " << typeNameAsVar << " { using type = ";
			stream << GetAccessibleTypeName(field.GetType(), field.GetTypeAsString());
			stream << " " << GetAccessibleTypeName(&class_, class_.GetQualifiedName()) << "::*; };\n";
			stream << "template struct Oyl::Reflection::Internal::StealMember<" << typeNameAsVar << ", &" << field.GetQualifiedName() << ">;\n";
		}

		for (const auto& function : class_.GetFunctions())
		{
			if (!function.ShouldReflect() || isPublic(function.GetAccessSpecifier()) || function.IsDeleted())
				continue;

			auto typeNameAsVar = GetStolenMemberTypeName(function);

			stream << "struct " << typeNameAsVar << " { using type = ";
			stream << GetAccessibleTypeName(function.GetReturnType(), function.GetReturnTypeAsString()) << "(*)(";
			const auto& args = function.GetArguments();
			for (size_t i = 0; i < args.size(); i++)
			{
				const auto& arg = args[i];
				stream << GetAccessibleTypeName(arg.GetType(), arg.GetTypeAsString());
				if (i != args.size() - 1)
				{
					stream << ", ";
				}
			}
			stream << "); };\n";
			stream << "template struct Oyl::Reflection::Internal::StealMember<" << typeNameAsVar << ", &" << function.GetQualifiedName() << ">;\n";
		}

		for (const auto& method : class_.GetMethods())
		{
			if (!method.ShouldReflect() || isPublic(method.GetAccessSpecifier()) || method.IsDeleted())
				continue;

			auto typeNameAsVar = GetStolenMemberTypeName(method);

			stream << "struct " << typeNameAsVar << " { using type = ";
			stream << GetAccessibleTypeName(method.GetReturnType(), method.GetReturnTypeAsString()) << "(" << class_.GetQualifiedName() << "::*)(";
			const auto& args = method.GetArguments();
			for (size_t i = 0; i < args.size(); i++)
			{
				const auto& arg = args[i];
				stream << GetAccessibleTypeName(arg.GetType(), arg.GetTypeAsString());
				if (i != args.size() - 1)
				{
					stream << ", ";
				}
			}
			stream << ")";
			if (method.IsConst())
			{
				stream << " const";
			}
			stream << "; };\n";
			stream << "template struct Oyl::Reflection::Internal::StealMember<" << typeNameAsVar << ", &" << method.GetQualifiedName() << ">;\n";
		}
	}

	FindAndReplace(a_emitString, "{REFLECT_STEAL_MEMBERS}", stream.str());
}

static std::unordered_set<const Spyll::Declaration*> g_privateAddressableDeclarations;

static
bool
IsDeclarationPrivate(const Spyll::Declaration& a_decl)
{
	return a_decl.GetAccessSpecifier() == Spyll::AccessSpecifier::Protected
	       || a_decl.GetAccessSpecifier() == Spyll::AccessSpecifier::Private;
}

std::string
GetAccessibleTypeName(const Spyll::Type* a_type, std::string_view a_typeAsString)
{
	std::string qualifiedType = std::string(a_typeAsString);

	if (!a_type)
		return qualifiedType;

	if (IsDeclarationPrivate(*a_type))
	{
		qualifiedType = GetSmuggledTypeAsTypeName(qualifiedType);
		g_typesToSmuggle.insert(a_typeAsString);
	}

	return qualifiedType;
}

void
RegisterTypes(std::stringstream& a_stream, const Spyll::ReflectionParser* a_parser)
{
	for (const auto& type : a_parser->GetClasses())
	{
		if (!type.ShouldReflect())
			continue;

		if (a_stream.tellp() != 0)
		{
			a_stream << "\n";
		}

		std::string typeVar = GetTypeNameAsVar(type.GetQualifiedName());

		std::string emitString = std::string(
			GetTrimmedStringView(R"""(
Oyl::Reflection::Type* {TYPENAME_AS_VAR}; (void) {TYPENAME_AS_VAR};
{
	Oyl::Reflection::Internal::TypeParams TypeParams;
	TypeParams.assembly = {ASSEMBLY_PTR};
	TypeParams.typeId = Oyl::Reflection::GetTypeId<{QUALIFIED_TYPENAME}>();
	TypeParams.qualifiedName = "{QUALIFIED_TYPENAME}";
	TypeParams.name = "{TYPENAME}";
	TypeParams.size = {SIZE};
	TypeParams.alignment = {ALIGNMENT};
	{TYPENAME_AS_VAR} = Oyl::Reflection::Internal::ReflectionFactory::AddTypeToAssembly({ASSEMBLY_PTR}, TypeParams, a_allocate);
}
)"""
			));

		FindAndReplace(emitString, "{ASSEMBLY_PTR}", "AssemblyPtr");
		FindAndReplace(emitString, "{QUALIFIED_TYPENAME}", type.GetQualifiedName());
		FindAndReplace(emitString, "{TYPENAME}", type.GetName());
		FindAndReplace(emitString, "{SIZE}", std::to_string(type.GetSize()));
		FindAndReplace(emitString, "{ALIGNMENT}", std::to_string(type.GetAlignment()));
		FindAndReplace(emitString, "{TYPENAME_AS_VAR}", GetTypeNameAsVar(type.GetQualifiedName()));

		a_stream << emitString;
	}
}

void
RegisterArgumentForFunction(
	std::stringstream& a_stream,
	const Spyll::Argument& a_argument
)
{
	std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::ArgumentParams Params;
	Params.type = Oyl::Reflection::Type::Get<{TYPE}>();
	Params.name = "{NAME}";
	Oyl::Reflection::Internal::ReflectionFactory::AddArgumentToInvokable(Ptr, Params, a_allocate);
}
)"""
	).data();

	FindAndReplace(emitString, "{TYPE}", GetAccessibleTypeName(a_argument.GetType(), a_argument.GetTypeAsString()));
	FindAndReplace(emitString, "{NAME}", a_argument.GetName());
	FindAndReplace(emitString, "{PTR}", "Ptr");

	a_stream << emitString;
}

void
RegisterVariable(
	std::stringstream& a_stream,
	const Spyll::Variable& a_variable,
	const Spyll::Class* a_parent
)
{
	if (!a_variable.ShouldReflect())
		return;

	if (IsDeclarationPrivate(a_variable))
		g_privateAddressableDeclarations.insert(&a_variable);

	std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::VariableParams Params;
	Params.qualifiedName = "{QUALIFIED_NAME}";
	Params.name = "{NAME}";
	Params.type = Oyl::Reflection::Type::Get<{QUALIFIED_TYPE}>();
	Params.parentType = {PARENT_TYPENAME_AS_VAR};
	Params.accessSpecifier = Oyl::Reflection::AccessSpecifier::{ACCESS_SPECIFIER};
	[[maybe_unused]] auto Ptr = {FACTORY_ADD_CALL};
}
)"""
	).data();

	std::string qualifiedType = GetAccessibleTypeName(a_variable.GetType(), a_variable.GetTypeAsString());

	std::string parentTypeNameAsVar = "nullptr";
	std::string factoryAddCall;

	if (a_parent)
	{
		parentTypeNameAsVar = GetTypeNameAsVar(a_parent->GetQualifiedName());
		factoryAddCall = "Oyl::Reflection::Internal::ReflectionFactory::AddVariableToType({PARENT_TYPENAME_AS_VAR}, Params, a_allocate)";
	} else
	{
		factoryAddCall = "Oyl::Reflection::Internal::ReflectionFactory::AddGlobalVariableToAssembly(AssemblyPtr, Params, a_allocate)";
	}

	FindAndReplace(emitString, "{FACTORY_ADD_CALL}", factoryAddCall);

	FindAndReplace(emitString, "{QUALIFIED_NAME}", a_variable.GetQualifiedName());
	FindAndReplace(emitString, "{NAME}", a_variable.GetName());
	FindAndReplace(emitString, "{QUALIFIED_TYPE}", qualifiedType);
	FindAndReplace(emitString, "{PARENT_TYPENAME_AS_VAR}", parentTypeNameAsVar);
	FindAndReplace(emitString, "{ACCESS_SPECIFIER}", std::to_string(a_variable.GetAccessSpecifier()));

	// Attributes soon:tm:

	a_stream << emitString;
}

void
RegisterField(
	std::stringstream& a_stream,
	const Spyll::Field& a_field,
	const Spyll::Class* a_parent
)
{
	if (!a_field.ShouldReflect())
		return;

	if (IsDeclarationPrivate(a_field))
		g_privateAddressableDeclarations.insert(&a_field);

	std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::FieldParams Params;
	Params.qualifiedName = "{QUALIFIED_NAME}";
	Params.name = "{NAME}";
	Params.type = Oyl::Reflection::Type::Get<{QUALIFIED_TYPE}>();
	Params.parentType = {PARENT_TYPENAME_AS_VAR};
	Params.accessSpecifier = Oyl::Reflection::AccessSpecifier::{ACCESS_SPECIFIER};
	Params.offsetInBits = {OFFSET_IN_BITS};
	Params.isConst = {IS_CONST};
	[[maybe_unused]] auto Ptr = Oyl::Reflection::Internal::ReflectionFactory::AddFieldToType({PARENT_TYPENAME_AS_VAR}, Params, a_allocate);
}
)"""
	).data();

	std::string qualifiedType = GetAccessibleTypeName(a_field.GetType(), a_field.GetTypeAsString());

	std::string parentTypeNameAsVar = a_parent ? GetTypeNameAsVar(a_parent->GetQualifiedName()) : "nullptr";

	FindAndReplace(emitString, "{QUALIFIED_NAME}", a_field.GetQualifiedName());
	FindAndReplace(emitString, "{NAME}", a_field.GetName());
	FindAndReplace(emitString, "{QUALIFIED_TYPE}", qualifiedType);
	FindAndReplace(emitString, "{PARENT_TYPENAME_AS_VAR}", parentTypeNameAsVar);
	FindAndReplace(emitString, "{ACCESS_SPECIFIER}", std::to_string(a_field.GetAccessSpecifier()));
	FindAndReplace(emitString, "{OFFSET_IN_BITS}", std::to_string(a_field.GetOffsetInBits()));
	FindAndReplace(emitString, "{IS_CONST}", a_field.IsConst() ? "true" : "false");

	// Attributes soon:tm:

	a_stream << emitString;
}

std::string
RegisterFunction_GetRawFunctionString(const Spyll::Function& a_function, const Spyll::Class* a_class)
{
	std::string result = GetTrimmedStringView(R"""(
{
	{RETURN_TYPE}({METHOD_PTR_STUB}*address)({RAW_SIGNATURE}){CONST} = {RAW_FN_ADDRESS};
	Params.rawFnPtr = *reinterpret_cast<void**>(&address);
}
	)"""
	).data();

	std::string methodPtrStub;
	std::string methodConst;
	const auto* method = dynamic_cast<const Spyll::Method*>(&a_function);
	if (method)
	{
		methodPtrStub = GetAccessibleTypeName(a_class, a_class->GetQualifiedName()) + "::";
		if (method->IsConst())
			methodConst = " const";
	}
	FindAndReplace(result, "{METHOD_PTR_STUB}", methodPtrStub);
	FindAndReplace(result, "{CONST}", methodConst);

	// Construct the signature of the raw function type
	std::stringstream argSignature;
	for (size_t i = 0; i < a_function.GetArguments().size(); i++)
	{
		const auto& arg = a_function.GetArguments()[i];
		argSignature << GetAccessibleTypeName(arg.GetType(), arg.GetTypeAsString());

		// Add comma unless it's the last arg
		if (i < a_function.GetArguments().size() - 1)
			argSignature << ", ";
	}
	FindAndReplace(result, "{RAW_SIGNATURE}", argSignature.str());

	std::stringstream rawAddress;
	if (!IsDeclarationPrivate(a_function))
	{
		// Namespace::Function
		rawAddress << "&" << a_function.GetQualifiedName();
	} else
	{
		// (Oyl::Reflection::Internal::StolenMember<__Stolen_Namespace_Function>::value)
		rawAddress << (method
			               ? StolenMember(*method)
			               : StolenMember(a_function));
	}
	FindAndReplace(result, "{RAW_FN_ADDRESS}", rawAddress.str());

	return result;
}

std::string
RegisterFunction_GetTypesafeFunctionString(const Spyll::Function& a_function, const Spyll::Class* a_class)
{
	std::string result = GetTrimmedStringView(R"""(
{
	auto thunkLambda = []({TYPESAFE_NAME_SIGNATURE}) -> std::any
	{
{TYPESAFE_ANY_CALL}
	};
	std::any(*thunkFnPtr)({TYPESAFE_TYPE_SIGNATURE}) = thunkLambda;
	Params.typeSafeThunkFnPtr = reinterpret_cast<void*>(thunkFnPtr);
}
)"""
	).data();

	const auto* method = dynamic_cast<const Spyll::Method*>(&a_function);

	const auto& args = a_function.GetArguments();
	std::string_view std_any_ref = "std::any&";

	// Function arguments signature with names
	// (std::any& arg1, std::any& arg2, ...)
	std::stringstream nameSignature;
	if (method)
		nameSignature << "std::any& __a_self";
	for (size_t i = 0; i < args.size(); i++)
	{
		if (method || i != 0)
			nameSignature << ", ";

		const auto& arg = args[i];
		nameSignature << std_any_ref << " " << arg.GetName();
	}
	FindAndReplace(result, "{TYPESAFE_NAME_SIGNATURE}", nameSignature.str());

	// Function arguments signature without names
	// (std::any&, std::any&, ...)
	std::stringstream typeSignature;
	if (method)
		typeSignature << "std::any&";
	for (size_t i = 0; i < args.size(); i++)
	{
		if (method || i != 0)
			typeSignature << ", ";

		typeSignature << std_any_ref;
	}
	FindAndReplace(result, "{TYPESAFE_TYPE_SIGNATURE}", typeSignature.str());

	std::stringstream callStatement;
	{
		std::string callFunc = "({SELF}{FN_PTR_DEREFERENCE}{FN_NAME})";

		std::string functionName = IsDeclarationPrivate(a_function)
			                           // *(Oyl::Reflection::Internal::StolenMember<__Stolen_Namespace_Function>::value)
			                           ? method ? StolenMember(*method) : StolenMember(a_function)
			                           // Namespace::Function
			                           : std::string(a_function.GetQualifiedName());

		FindAndReplace(callFunc, "{SELF}", method ? "__self->" : "");
		FindAndReplace(callFunc, "{FN_PTR_DEREFERENCE}", method && IsDeclarationPrivate(a_function) ? "*" : "");
		FindAndReplace(callFunc, "{FN_NAME}", functionName);

		callStatement << callFunc;
	}
	callStatement << "(";
	for (size_t i = 0; i < args.size(); i++)
	{
		const auto& arg = args[i];

		callStatement << "\n";
		std::string declaration = "\tstd::any_cast<{TYPE}>({NAME})";
		FindAndReplace(declaration, "{TYPE}", GetAccessibleTypeName(arg.GetType(), arg.GetTypeAsString()));
		FindAndReplace(declaration, "{NAME}", arg.GetName());
		callStatement << declaration;

		if (i != args.size() - 1)
			callStatement << ", ";
	}
	callStatement << ")";

	std::stringstream callReturn;
	if (method)
		callReturn << "auto __self = std::any_cast<" << a_class->GetQualifiedName() << "*>(__a_self);\n";
	if (a_function.GetReturnTypeAsString() == "void")
	{
		callReturn << callStatement.str() << ";\n";
		callReturn << "return std::any {};";
	} else
	{
		callReturn << "std::any result = " << callStatement.str() << ";\n";
		callReturn << "return result;";
	}
	AddIndentToStringStream(callReturn, "\t\t");
	FindAndReplace(result, "{TYPESAFE_ANY_CALL}", callReturn.str());

	return result;
}

void
RegisterFunction(
	std::stringstream& a_stream,
	const Spyll::Function& a_function,
	const Spyll::Class* a_class
)
{
	if (!a_function.ShouldReflect())
		return;

	if (IsDeclarationPrivate(a_function))
		g_privateAddressableDeclarations.insert(&a_function);

	std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::{FUNC_KIND}Params Params;
	Params.qualifiedName = "{QUALIFIED_NAME}";
	Params.name = "{NAME}";
	Params.returnType = Oyl::Reflection::Type::Get<{RETURN_TYPE}>();
	Params.parentType = {PARENT_TYPENAME_AS_VAR};
	Params.accessSpecifier = Oyl::Reflection::AccessSpecifier::{ACCESS_SPECIFIER};
{METHOD_PARAMS}
{RAW_FN_PTR}
{TYPESAFE_FN_PTR}
	[[maybe_unused]] auto Ptr = Oyl::Reflection::Internal::ReflectionFactory::Add{FUNC_KIND}ToType({PARENT_TYPENAME_AS_VAR}, Params, a_allocate);
{ARGUMENTS}
}
)"""
	).data();

	std::string qualifiedReturnType = GetAccessibleTypeName(a_function.GetReturnType(), a_function.GetReturnTypeAsString());

	std::string funcKind = "Function";
	std::string methodParams;
	std::string parentTypeNameAsVar = "nullptr";
	std::string factoryAddCall;

	if (a_class)
	{
		parentTypeNameAsVar = GetTypeNameAsVar(a_class->GetQualifiedName());
		factoryAddCall = "Oyl::Reflection::Internal::ReflectionFactory::Add{FUNC_KIND}ToType({PARENT_TYPENAME_AS_VAR}, Params, a_allocate)";
	} else
	{
		factoryAddCall = "Oyl::Reflection::Internal::ReflectionFactory::AddGlobalFunctionToAssembly(AssemblyPtr, Params, a_allocate)";
	}

	const auto* method = dynamic_cast<const Spyll::Method*>(&a_function);
	if (method)
	{
		funcKind = "Method";
		std::stringstream s;
		s << "\tParams.isConst = " << (method->IsConst() ? "true" : "false") << ";\n";
		s << "\tParams.isVirtual = " << (method->IsVirtual() ? "true" : "false") << ";";
		methodParams = std::move(s.str());
	}

	std::string rawFnPtrString;
	std::string typesafeFnPtrString;
	if (!a_function.IsDeleted())
	{
		rawFnPtrString = RegisterFunction_GetRawFunctionString(a_function, a_class);
		typesafeFnPtrString = RegisterFunction_GetTypesafeFunctionString(a_function, a_class);
	}

	FindAndReplace(emitString, "{RAW_FN_PTR}", rawFnPtrString);
	FindAndReplace(emitString, "{TYPESAFE_FN_PTR}", typesafeFnPtrString);

	FindAndReplace(emitString, "{FACTORY_ADD_CALL}", factoryAddCall);

	FindAndReplace(emitString, "{FUNC_KIND}", funcKind);
	FindAndReplace(emitString, "{QUALIFIED_NAME}", a_function.GetQualifiedName());
	FindAndReplace(emitString, "{NAME}", a_function.GetName());
	FindAndReplace(emitString, "{RETURN_TYPE}", qualifiedReturnType);
	FindAndReplace(emitString, "{PARENT_TYPENAME_AS_VAR}", parentTypeNameAsVar);
	FindAndReplace(emitString, "{ACCESS_SPECIFIER}", std::to_string(a_function.GetAccessSpecifier()));
	FindAndReplace(emitString, "{METHOD_PARAMS}", methodParams);

	std::stringstream argumentsStream;
	for (const auto& argument : a_function.GetArguments())
		RegisterArgumentForFunction(argumentsStream, argument);
	AddIndentToStringStream(argumentsStream);
	FindAndReplace(emitString, "{ARGUMENTS}", argumentsStream.str());

	// Attributes

	a_stream << emitString;
}

void
RegisterEnums(std::stringstream& a_stream, const Spyll::ReflectionParser* a_parser)
{
	for (const auto& enum_ : a_parser->GetEnums())
	{
		if (!enum_.ShouldReflect())
			continue;

		std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::EnumParams EnumParams;
	EnumParams.qualifiedName = "{QUALIFIED_NAME}";
	EnumParams.name = "{NAME}";
	EnumParams.underlyingType = Oyl::Reflection::Type::Get<{UNDERLYING_TYPE}>();
	EnumParams.nValues = static_cast<size_t>({SIZE});
	[[maybe_unused]] auto Ptr = Oyl::Reflection::Internal::ReflectionFactory::AddEnumToAssembly(AssemblyPtr, EnumParams, a_allocate);
{ENTRIES}
}
)"""
		).data();

		FindAndReplace(emitString, "{QUALIFIED_NAME}", enum_.GetQualifiedName());
		FindAndReplace(emitString, "{NAME}", enum_.GetName());
		FindAndReplace(emitString, "{UNDERLYING_TYPE}", enum_.GetUnderlyingTypeAsString());
		FindAndReplace(emitString, "{SIZE}", std::to_string(enum_.GetEntries().size()));

		std::stringstream entryStream;
		for (const auto& entry : enum_.GetEntries())
		{
			std::string entryString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::EnumValueParams EnumValueParams;
	EnumValueParams.identifier = "{IDENTIFIER}";
	EnumValueParams.value = static_cast<{UNDERLYING_TYPE}>({VALUE});
	Oyl::Reflection::Internal::ReflectionFactory::AddValueToEnum(Ptr, EnumValueParams, a_allocate);
}
)"""
			).data();

			FindAndReplace(entryString, "{IDENTIFIER}", entry.GetIdentifier());
			FindAndReplace(entryString, "{VALUE}", std::to_string(entry.GetValue()));
			FindAndReplace(entryString, "{UNDERLYING_TYPE}", enum_.GetUnderlyingTypeAsString());

			entryStream << entryString;
		}

		AddIndentToStringStream(entryStream);
		FindAndReplace(emitString, "{ENTRIES}", entryStream.str());

		a_stream << emitString;
	}
}
