#include "Emit.h"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <unordered_set>

#include <Spyll/Tool/Core/ReflectionParser.h>

#include "DeclPrinter.h"
#include "SpyllTool.h"
#include "StringHelper.h"

void
EmitHeaderComment(std::string& a_emitString);

void
EmitIncludes(std::string& a_emitString, const Spyll::ReflectionParser* a_parser);

void
EmitDependencies(std::string& a_emitString, const std::vector<std::string_view>& a_tool);

void
EmitReflectionRegister(std::string& a_emitString, const Spyll::ReflectionParser* a_parser);

void
EmitTypeSmuggleDeclarations(std::string& a_emitString, const Spyll::ReflectionParser* a_parser);

void
EmitMemberStealDeclarations(std::string& a_emitString, const Spyll::ReflectionParser* a_parser);

void
RegisterTypes(std::stringstream& a_stream, const Spyll::ReflectionParser* a_parser);

void
RegisterVariablesForType(
	std::stringstream& a_stream,
	const Spyll::Type& a_parentType
);

void
RegisterFieldsForType(
	std::stringstream& a_stream,
	const Spyll::Type& a_parentType
);

void
RegisterFunctionsForType(
	std::stringstream& a_stream,
	const Spyll::Type& a_parentType
);

void
RegisterMethodsForType(
	std::stringstream& a_stream,
	const Spyll::Type& a_parentType
);

void
RegisterArgumentForFunction(
	std::stringstream& a_stream,
	const Spyll::Function& a_function
);

void
RegisterGlobalVariables(
	std::stringstream& a_stream,
	const Spyll::ReflectionParser* a_parser
);

void
RegisterGlobalFunctions(
	std::stringstream& a_stream,
	const Spyll::ReflectionParser* a_parser
);

void
RegisterEnums(
	std::stringstream& a_stream,
	const Spyll::ReflectionParser* a_parser
);

constexpr
static
std::string_view g_emitTemplate = GetTrimmedStringView(R"""(
{HEADER_COMMENT}

#include <Core/Reflection/ReflectionFactory.h>

{REFLECT_INCLUDES}

{REFLECT_SMUGGLE_TYPES}

{REFLECT_STEAL_MEMBERS}

extern "C"
_OYL_EXPORT
void
_ReflectionAssembly_Dependencies(int* a_count, const char*** a_dependencies)
{
	*a_count = {DEPENDENCY_COUNT};

{DEPENDENCIES}
	*a_dependencies = dependencies;
}

extern "C"
_OYL_EXPORT
::Oyl::Reflection::Assembly*
_ReflectionAssembly_Register(::Oyl::Reflection::Internal::ReflectionAllocatorFn a_allocate)
{
	Oyl::Reflection::Internal::AssemblyParams AssemblyParams;
	AssemblyParams.name = "{ASSEMBLY_NAME}";
	Oyl::Reflection::Assembly* AssemblyPtr = Oyl::Reflection::Internal::ReflectionFactory::CreateAssembly(AssemblyParams, a_allocate);

{REFLECTION_REGISTER}

	return AssemblyPtr;
}
)""");

void
EmitCodeFromTool(const Spyll::ReflectionParser* a_parser)
{
	std::filesystem::create_directory(".Generated");

	std::ofstream generatedIncludeFile;
	generatedIncludeFile.open(".Generated/Spyll.generated.cpp");

	std::string emitString = std::string(g_emitTemplate);

	EmitReflectionRegister(emitString, a_parser);

	EmitHeaderComment(emitString);
	EmitIncludes(emitString, a_parser);
	EmitDependencies(emitString, g_tool.dependencies);
	EmitMemberStealDeclarations(emitString, a_parser);

	FindAndReplace(emitString, "{ASSEMBLY_NAME}", g_tool.assemblyName);

	generatedIncludeFile << emitString;
}

void
EmitHeaderComment(std::string& a_emitString)
{
	std::string_view result =
		"// Auto-Generated Source File, Generated by Oyl.Spyll\n"
		"// {GENERATION_DATE}\n"
		"// DO NOT MODIFY!\n";

	FindAndReplace(a_emitString, "{HEADER_COMMENT}", result);
}

void
EmitIncludes(std::string& a_emitString, const Spyll::ReflectionParser* a_parser)
{
	std::unordered_set<std::string_view> includeSet;

	for (const Spyll::Type& type : a_parser->GetTypes())
	{
		includeSet.insert(type.GetSourceFile());
	}

	for (const Spyll::Variable& variable : a_parser->GetGlobalVariables())
	{
		includeSet.insert(variable.GetSourceFile());
	}

	for (const Spyll::Function& function : a_parser->GetGlobalFunctions())
	{
		includeSet.insert(function.GetSourceFile());
	}

	for (const Spyll::Enum& enum_ : a_parser->GetEnums())
	{
		includeSet.insert(enum_.GetSourceFile());
	}

	std::stringstream includes;
	for (const auto& include : includeSet)
	{
		includes << "#include <" << include << ">\n";
	}
	FindAndReplace(a_emitString, "{REFLECT_INCLUDES}", includes.str());
}

void
EmitDependencies(std::string& a_emitString, const std::vector<std::string_view>& a_dependencies)
{
	std::stringstream dependenciesArr;
	if (a_dependencies.empty())
	{
		dependenciesArr << "static const char** dependencies = nullptr";
	} else
	{
		dependenciesArr << "static const char* dependencies[] = { \n";
		for (const auto& dependency : a_dependencies)
		{
			dependenciesArr << "\t\"" << dependency << "\"" << ",\n";
		}
		dependenciesArr << "}";
	}
	dependenciesArr << ";\n";

	AddIndentToStringStream(dependenciesArr);
	FindAndReplace(a_emitString, "{DEPENDENCIES}", dependenciesArr.str());
	FindAndReplace(a_emitString, "{DEPENDENCY_COUNT}", std::to_string(a_dependencies.size()));
}

void
EmitReflectionRegister(std::string& a_emitString, const Spyll::ReflectionParser* a_parser)
{
	std::stringstream stream;
	stream.setf(std::ios::boolalpha);

	RegisterTypes(stream, a_parser);
	RegisterEnums(stream, a_parser);

	// Register type children after all types registered to guarantee calls to Type::Get<T>() succeed
	for (const auto& type : a_parser->GetTypes())
	{
		RegisterVariablesForType(stream, type);
		RegisterFieldsForType(stream, type);
		RegisterFunctionsForType(stream, type);
		RegisterMethodsForType(stream, type);
	}

	RegisterGlobalVariables(stream, a_parser);
	RegisterGlobalFunctions(stream, a_parser);

	AddIndentToStringStream(stream);
	FindAndReplace(a_emitString, "{REFLECTION_REGISTER}", stream.str());
}

void
EmitTypeSmuggleDeclarations(std::string& a_emitString, const Spyll::ReflectionParser* a_parser)
{
	std::stringstream stream;
	stream.setf(std::ios::boolalpha);

	std::string emitString = std::string(
		GetTrimmedStringView(R"""(
namespace
{
	template<typename... Types>
	struct TypeSmuggler
	{
		using tuple_t = std::tuple<Types...>;

		template<size_t Index>
		using element_t = std::tuple_element_t<Index, tuple_t>;

{FRIEND_INJECTIONS}

		friend auto __Smuggler__Oyl_CommandLine_Impl() { return reinterpret_cast<std::add_pointer_t<element_t<0>>>(nullptr); };
		friend auto __Smuggler__Oyl_EventDispatcher_ListenerList() { return reinterpret_cast<std::add_pointer_t<element_t<1>>>(nullptr); };
		friend auto __Smuggler__Oyl_EventDispatcher_ListenerDescriptor() { return reinterpret_cast<std::add_pointer_t<element_t<2>>>(nullptr); };
		friend auto __Smuggler__Oyl_Internal_ResourceHandleBase_Tag() { return reinterpret_cast<std::add_pointer_t<element_t<3>>>(nullptr); };
	};

	template struct TypeSmuggler<
{TYPES_TO_SMUGGLE}
		Oyl::CommandLine::Impl,
		Oyl::EventDispatcher::ListenerList,
		Oyl::EventDispatcher::ListenerDescriptor,
		Oyl::Internal::ResourceHandleBase::Tag
	>;

{SMUGGLE_DECLARATIONS}

	auto __Smuggler__Oyl_CommandLine_Impl();
	using __Smuggled__Oyl_CommandLine_Impl = std::remove_pointer_t<decltype(__Smuggler__Oyl_CommandLine_Impl())>;
	auto __Smuggler__Oyl_EventDispatcher_ListenerList();
	using __Smuggled__Oyl_EventDispatcher_ListenerList = std::remove_pointer_t<decltype(__Smuggler__Oyl_EventDispatcher_ListenerList())>;
	auto __Smuggler__Oyl_EventDispatcher_ListenerDescriptor();
	using __Smuggled__Oyl_EventDispatcher_ListenerDescriptor = std::remove_pointer_t<decltype(__Smuggler__Oyl_EventDispatcher_ListenerDescriptor())>;
	auto __Smuggler__Oyl_Internal_ResourceHandleBase_Tag();
	using __Smuggled__Oyl_Internal_ResourceHandleBase_Tag = std::remove_pointer_t<decltype(__Smuggler__Oyl_Internal_ResourceHandleBase_Tag())>;
}
)"""
		));

	std::stringstream friendInjections;
	std::stringstream typesToSmuggle;
	std::stringstream smuggleDeclarations;

	for (const auto& type : a_parser->GetTypes())
	{
		// We only need to smuggle non-publicly accessible types
		if (type.GetAccessSpecifier() == Spyll::AccessSpecifier::Public
		    || type.GetAccessSpecifier() == Spyll::AccessSpecifier::None)
		{
			continue;
		}

		FindAndReplace(emitString, "{ASSEMBLY_PTR}", "AssemblyPtr");
		FindAndReplace(emitString, "{QUALIFIED_TYPENAME}", type.GetQualifiedName());
		FindAndReplace(emitString, "{TYPENAME}", type.GetName());
		FindAndReplace(emitString, "{SIZE}", std::to_string(type.GetSize()));
		FindAndReplace(emitString, "{ALIGNMENT}", std::to_string(type.GetAlignment()));
		FindAndReplace(emitString, "{TYPENAME_AS_VAR}", GetTypeNameAsVar(type.GetQualifiedName()));

		stream << emitString;
	}

	FindAndReplace(a_emitString, "{REFLECT_SMUGGLE_TYPES}", stream.str());
}

void
EmitMemberStealDeclarations(std::string& a_emitString, const Spyll::ReflectionParser* a_parser)
{
	std::stringstream stream;
	stream.setf(std::ios::boolalpha);

	auto isPublic = [](Spyll::AccessSpecifier a_accessSpec)
	{
		return a_accessSpec == Spyll::AccessSpecifier::Public;
	};

	for (const auto& type : a_parser->GetTypes())
	{
		for (const auto& variable : type.GetVariables())
		{
			if (!variable.ShouldReflect() || isPublic(variable.GetAccessSpecifier()))
				continue;

			auto typeNameAsVar = GetStolenMemberTypeName(variable);

			stream << "struct " << typeNameAsVar << " { using type = ";
			stream << variable.GetTypeAsString() << "*; };\n";
			stream << "template struct Oyl::Reflection::Internal::StealMember<" << typeNameAsVar << ", &" << variable.GetQualifiedName() << ">;\n";
		}

		for (const auto& field : type.GetFields())
		{
			if (!field.ShouldReflect() || isPublic(field.GetAccessSpecifier()))
				continue;

			auto typeNameAsVar = GetStolenMemberTypeName(field);

			stream << "struct " << typeNameAsVar << " { using type = ";
			stream << field.GetTypeAsString() << "(" << type.GetQualifiedName() << "::*); };\n";
			stream << "template struct Oyl::Reflection::Internal::StealMember<" << typeNameAsVar << ", &" << field.GetQualifiedName() << ">;\n";
		}

		for (const auto& function : type.GetFunctions())
		{
			if (!function.ShouldReflect() || isPublic(function.GetAccessSpecifier()) || function.IsDeleted())
				continue;

			auto typeNameAsVar = GetStolenMemberTypeName(function);

			stream << "struct " << typeNameAsVar << " { using type = ";
			stream << function.GetReturnTypeAsString() << "(*)(";
			const auto& args = function.GetArguments();
			for (size_t i = 0; i < args.size(); i++)
			{
				const auto& arg = args[i];
				stream << arg.GetTypeAsString();
				if (i != args.size() - 1)
				{
					stream << ", ";
				}
			}
			stream << "); };\n";
			stream << "template struct Oyl::Reflection::Internal::StealMember<" << typeNameAsVar << ", &" << function.GetQualifiedName() << ">;\n";
		}

		for (const auto& method : type.GetMethods())
		{
			if (!method.ShouldReflect() || isPublic(method.GetAccessSpecifier()) || method.IsDeleted())
				continue;

			auto typeNameAsVar = GetStolenMemberTypeName(method);

			stream << "struct " << typeNameAsVar << " { using type = ";
			stream << method.GetReturnTypeAsString() << "(" << type.GetQualifiedName() << "::*)(";
			const auto& args = method.GetArguments();
			for (size_t i = 0; i < args.size(); i++)
			{
				const auto& arg = args[i];
				stream << arg.GetTypeAsString();
				if (i != args.size() - 1)
				{
					stream << ", ";
				}
			}
			stream << ")";
			if (method.IsConst())
			{
				stream << " const";
			}
			stream << "; };\n";
			stream << "template struct Oyl::Reflection::Internal::StealMember<" << typeNameAsVar << ", &" << method.GetQualifiedName() << ">;\n";
		}
	}

	FindAndReplace(a_emitString, "{REFLECT_STEAL_MEMBERS}", stream.str());
}

static std::vector<const Spyll::Declaration*> g_privateTypes;
static std::vector<const Spyll::Declaration*> g_privateAddressableDeclarations;

static
bool
IsDeclarationPrivate(const Spyll::Declaration& a_decl)
{
	return a_decl.GetAccessSpecifier() == Spyll::AccessSpecifier::Protected
	       || a_decl.GetAccessSpecifier() == Spyll::AccessSpecifier::Private;
}

void
RegisterTypes(std::stringstream& a_stream, const Spyll::ReflectionParser* a_parser)
{
	for (const auto& type : a_parser->GetTypes())
	{
		if (!type.ShouldReflect())
			continue;

		if (a_stream.tellp() != 0)
		{
			a_stream << "\n";
		}

		std::string typeVar = GetTypeNameAsVar(type.GetQualifiedName());

		std::string emitString = std::string(
			GetTrimmedStringView(R"""(
Oyl::Reflection::Type* {TYPENAME_AS_VAR}; (void) {TYPENAME_AS_VAR};
{
	Oyl::Reflection::Internal::TypeParams TypeParams;
	TypeParams.assembly = {ASSEMBLY_PTR};
	TypeParams.typeId = Oyl::Reflection::GetTypeId<{QUALIFIED_TYPENAME}>();
	TypeParams.qualifiedName = "{QUALIFIED_TYPENAME}";
	TypeParams.name = "{TYPENAME}";
	TypeParams.size = {SIZE};
	TypeParams.alignment = {ALIGNMENT};
	{TYPENAME_AS_VAR} = Oyl::Reflection::Internal::ReflectionFactory::AddTypeToAssembly({ASSEMBLY_PTR}, TypeParams, a_allocate);
}
)"""
			));

		FindAndReplace(emitString, "{ASSEMBLY_PTR}", "AssemblyPtr");
		FindAndReplace(emitString, "{QUALIFIED_TYPENAME}", type.GetQualifiedName());
		FindAndReplace(emitString, "{TYPENAME}", type.GetName());
		FindAndReplace(emitString, "{SIZE}", std::to_string(type.GetSize()));
		FindAndReplace(emitString, "{ALIGNMENT}", std::to_string(type.GetAlignment()));
		FindAndReplace(emitString, "{TYPENAME_AS_VAR}", GetTypeNameAsVar(type.GetQualifiedName()));

		a_stream << emitString;
	}
}

void
RegisterVariablesForType(
	std::stringstream& a_stream,
	const Spyll::Type& a_parentType
)
{
	for (const auto& variable : a_parentType.GetVariables())
	{
		if (!variable.ShouldReflect())
			continue;

		if (IsDeclarationPrivate(variable))
			g_privateAddressableDeclarations.push_back(&variable);

		std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::VariableParams VariableParams;
	VariableParams.qualifiedName = "{QUALIFIED_NAME}";
	VariableParams.name = "{NAME}";
	VariableParams.type = Oyl::Reflection::Type::Get<{QUALIFIED_TYPE}>();
	VariableParams.parentType = {PARENT_TYPENAME_AS_VAR};
	VariableParams.accessSpecifier = Oyl::Reflection::AccessSpecifier::{ACCESS_SPECIFIER};
	Oyl::Reflection::Internal::ReflectionFactory::AddVariableToType({PARENT_TYPENAME_AS_VAR}, VariableParams, a_allocate);
}
)"""
		).data();

		std::string qualifiedType = std::string(variable.GetTypeAsString());
		if (IsDeclarationPrivate(variable))
		{
			g_privateAddressableDeclarations.push_back(&variable);
			qualifiedType = GetSmuggledTypeAsTypeName(qualifiedType);
		}

		FindAndReplace(emitString, "{QUALIFIED_NAME}", variable.GetQualifiedName());
		FindAndReplace(emitString, "{NAME}", variable.GetName());
		FindAndReplace(emitString, "{QUALIFIED_TYPE}", qualifiedType);
		FindAndReplace(emitString, "{ACCESS_SPECIFIER}", std::to_string(variable.GetAccessSpecifier()));
		FindAndReplace(emitString, "{PARENT_TYPENAME_AS_VAR}", GetTypeNameAsVar(a_parentType.GetQualifiedName()));

		a_stream << emitString;
	}
}

void
RegisterFieldsForType(
	std::stringstream& a_stream,
	const Spyll::Type& a_parentType
)
{
	for (const auto& field : a_parentType.GetFields())
	{
		if (!field.ShouldReflect())
			continue;

		std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::FieldParams FieldParams;
	FieldParams.qualifiedName = "{QUALIFIED_NAME}";
	FieldParams.name = "{NAME}";
	FieldParams.type = Oyl::Reflection::Type::Get<{QUALIFIED_TYPE}>();
	FieldParams.parentType = {PARENT_TYPENAME_AS_VAR};
	FieldParams.offsetInBits = {OFFSET_IN_BITS};
	FieldParams.accessSpecifier = Oyl::Reflection::AccessSpecifier::{ACCESS_SPECIFIER};
	FieldParams.isConst = {IS_CONST};
	{FIELD_PTR}Oyl::Reflection::Internal::ReflectionFactory::AddFieldToType({PARENT_TYPENAME_AS_VAR}, FieldParams, a_allocate);
{ATTRIBUTES}
}
)"""
		).data();

		std::string qualifiedType = std::string(field.GetTypeAsString());
		if (IsDeclarationPrivate(field))
		{
			g_privateAddressableDeclarations.push_back(&field);
			qualifiedType = GetSmuggledTypeAsTypeName(qualifiedType);
		}

		FindAndReplace(emitString, "{QUALIFIED_NAME}", field.GetQualifiedName());
		FindAndReplace(emitString, "{NAME}", field.GetName());
		FindAndReplace(emitString, "{QUALIFIED_TYPE}", field.GetTypeAsString());
		FindAndReplace(emitString, "{PARENT_TYPENAME_AS_VAR}", GetTypeNameAsVar(a_parentType.GetQualifiedName()));
		FindAndReplace(emitString, "{ACCESS_SPECIFIER}", std::to_string(field.GetAccessSpecifier()));
		FindAndReplace(emitString, "{OFFSET_IN_BITS}", std::to_string(field.GetOffsetInBits()));
		FindAndReplace(emitString, "{IS_CONST}", field.IsConst() ? "true" : "false");

		const auto& attrs = field.GetAttributes();
		std::stringstream attrStream;
		if (attrs.empty())
		{
			FindAndReplace(emitString, "{FIELD_PTR}", "");
		} else
		{
			FindAndReplace(emitString, "{FIELD_PTR}", "auto FieldPtr = ");
			for (const auto& attr : attrs)
			{
				std::string attrString = GetTrimmedStringView(R"""(
{
	auto Attribute = new {ATTR_TYPE}({ATTR_ARGS});
	Oyl::Reflection::Internal::ReflectionFactory::AddAttributeToDeclaration(FieldPtr, Attribute);
}
)"""
				).data();

				FindAndReplace(attrString, "{ATTR_TYPE}", attr.type);

				std::stringstream argStream;
				for (size_t i = 0; i < attr.arguments.size(); i++)
				{
					const auto& arg = attr.arguments[i];

					constexpr std::string_view typeIdMarker = "__TypeId";
					auto typeIdMarkerIndex = arg.find(typeIdMarker);
					if (typeIdMarkerIndex != std::string::npos)
					{
						auto typeId = arg.substr(typeIdMarker.length() + 1);
						argStream << "::Oyl::Reflection::GetTypeId<" << typeId << ">()";
					} else
					{
						argStream << arg;
					}

					if (i < attr.arguments.size() - 1)
						argStream << ", ";
				}

				FindAndReplace(attrString, "{ATTR_ARGS}", argStream.str());
				attrStream << attrString;
			}

			AddIndentToStringStream(attrStream);
		}

		FindAndReplace(emitString, "{ATTRIBUTES}", attrStream.str());

		a_stream << emitString;
	}
}

void
RegisterFunctionsForType(
	std::stringstream& a_stream,
	const Spyll::Type& a_parentType
)
{
	for (const auto& function : a_parentType.GetFunctions())
	{
		if (!function.ShouldReflect())
			continue;

		std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::FunctionParams FunctionParams;
	FunctionParams.qualifiedName = "{QUALIFIED_NAME}";
	FunctionParams.name = "{NAME}";
	FunctionParams.returnType = Oyl::Reflection::Type::Get<{RETURN_TYPE}>();
	FunctionParams.parentType = {PARENT_TYPENAME_AS_VAR};
	FunctionParams.accessSpecifier = Oyl::Reflection::AccessSpecifier::{ACCESS_SPECIFIER};
	{RETURN_TYPE}(*address)({ARG_SIGNATURE}) = {RAW_FN_ADDRESS};
	FunctionParams.rawFnPtr = *reinterpret_cast<void**>(&address);
{TYPESAFE_PTR}
	{INVOKABLE_PTR}Oyl::Reflection::Internal::ReflectionFactory::AddFunctionToType({PARENT_TYPENAME_AS_VAR}, FunctionParams, a_allocate);
{ARGUMENTS}
}
)"""
		).data();

		FindAndReplace(emitString, "{QUALIFIED_NAME}", function.GetQualifiedName());
		FindAndReplace(emitString, "{NAME}", function.GetName());
		FindAndReplace(emitString, "{RETURN_TYPE}", function.GetReturnTypeAsString());
		FindAndReplace(emitString, "{PARENT_TYPENAME_AS_VAR}", GetTypeNameAsVar(a_parentType.GetQualifiedName()));
		FindAndReplace(emitString, "{ACCESS_SPECIFIER}", std::to_string(function.GetAccessSpecifier()));
		FindAndReplace(emitString, "{INVOKABLE_PTR}", function.GetArguments().size() != 0 ? "auto InvokablePtr = " : "");

		std::stringstream argSignature;
		for (size_t i = 0; i < function.GetArguments().size(); i++)
		{
			const auto& arg = function.GetArguments()[i];
			argSignature << arg.GetTypeAsString();

			if (i < function.GetArguments().size() - 1)
				argSignature << ", ";
		}

		FindAndReplace(emitString, "{ARG_SIGNATURE}", argSignature.str());

		std::stringstream rawAddress;
		if (function.IsDeleted())
		{
			rawAddress << "nullptr";
		} else if (function.GetAccessSpecifier() == Spyll::AccessSpecifier::Public)
		{
			// Namespace::Function
			rawAddress << "&" << function.GetQualifiedName();
		} else
		{
			// (Oyl::Reflection::Internal::StolenMember<__Stolen_Namespace_Function>::value)
			rawAddress << StolenMember(function);
		}
		FindAndReplace(emitString, "{RAW_FN_ADDRESS}", rawAddress.str());

		std::string typesafePtrString = GetTrimmedStringView(R"""(
auto thunkLambda = []({NAME_SIGNATURE}) -> std::any
{
{RAW_CALL}
};
std::any(*thunkFnPtr)({TYPE_SIGNATURE}) = thunkLambda;
FunctionParams.typeSafeThunkFnPtr = reinterpret_cast<void*>(thunkFnPtr);
)"""
		).data();

		std::stringstream nameSignature;
		std::stringstream typeSignature;
		const auto& args = function.GetArguments();
		for (size_t i = 0; i < args.size(); i++)
		{
			const auto& arg = args[i];
			std::string_view std_any_ref = "std::any&";
			typeSignature << std_any_ref;
			nameSignature << std_any_ref << " " << arg.GetName();

			if (i != args.size() - 1)
			{
				typeSignature << ", ";
				nameSignature << ", ";
			}
		}
		FindAndReplace(typesafePtrString, "{NAME_SIGNATURE}", nameSignature.str());
		FindAndReplace(typesafePtrString, "{TYPE_SIGNATURE}", typeSignature.str());

		if (!function.IsDeleted())
		{
			std::stringstream callStatement;
			if (function.GetAccessSpecifier() == Spyll::AccessSpecifier::Public)
			{
				// Namespace::Function
				callStatement << function.GetQualifiedName();
			} else
			{
				// (Oyl::Reflection::Internal::StolenMember<__Stolen_Namespace_Function>::value)
				callStatement << StolenMember(function);
			}
			callStatement << "(" << (args.size() != 0 ? "\n" : "");
			for (size_t i = 0; i < args.size(); i++)
			{
				const auto& arg = args[i];

				std::string declaration = "\tstd::any_cast<{TYPE}>({NAME})";
				FindAndReplace(declaration, "{TYPE}", arg.GetTypeAsString());
				FindAndReplace(declaration, "{NAME}", arg.GetName());

				callStatement << declaration;
				if (i != args.size() - 1)
					callStatement << ", ";
				callStatement << "\n";
			}
			callStatement << ")";

			std::stringstream callReturn;
			if (function.GetReturnTypeAsString() == "void")
			{
				callReturn << callStatement.str() << ";\n";
				callReturn << "return std::any {};";
			} else
			{
				callReturn << "std::any result = " << callStatement.str() << ";\n";
				callReturn << "return result;";
			}
			AddIndentToStringStream(callReturn);
			FindAndReplace(typesafePtrString, "{RAW_CALL}", callReturn.str());
		} else
		{
			// Function is deleted, return empty any
			FindAndReplace(typesafePtrString, "{RAW_CALL}", "\treturn std::any {};");
		}

		std::stringstream typesafePtr;
		typesafePtr << typesafePtrString;
		AddIndentToStringStream(typesafePtr);
		FindAndReplace(emitString, "{TYPESAFE_PTR}", typesafePtr.str());

		std::stringstream argumentsStream;
		RegisterArgumentForFunction(argumentsStream, function);
		AddIndentToStringStream(argumentsStream);
		FindAndReplace(emitString, "{ARGUMENTS}", argumentsStream.str());

		a_stream << emitString;
	}
}

void
RegisterMethodsForType(
	std::stringstream& a_stream,
	const Spyll::Type& a_parentType
)
{
	for (const auto& method : a_parentType.GetMethods())
	{
		if (!method.ShouldReflect())
			continue;

		std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::MethodParams MethodParams;
	MethodParams.qualifiedName = "{QUALIFIED_NAME}";
	MethodParams.name = "{NAME}";
	MethodParams.returnType = Oyl::Reflection::Type::Get<{RETURN_TYPE}>();
	MethodParams.parentType = {PARENT_TYPENAME_AS_VAR};
	MethodParams.accessSpecifier = Oyl::Reflection::AccessSpecifier::{ACCESS_SPECIFIER};
	MethodParams.isConst = {IS_CONST};
	MethodParams.isVirtual = {IS_VIRTUAL};
	{RETURN_TYPE}({PARENT_QUALIFIED_NAME}::*address)({ARG_SIGNATURE}){FN_CONST_QUAL} = {RAW_FN_ADDRESS};
	MethodParams.rawFnPtr = *reinterpret_cast<void**>(&address);
{TYPESAFE_PTR}
	{INVOKABLE_PTR}Oyl::Reflection::Internal::ReflectionFactory::AddMethodToType({PARENT_TYPENAME_AS_VAR}, MethodParams, a_allocate);
{ARGUMENTS}
}
)"""
		).data();

		FindAndReplace(emitString, "{QUALIFIED_NAME}", method.GetQualifiedName());
		FindAndReplace(emitString, "{NAME}", method.GetName());
		FindAndReplace(emitString, "{RETURN_TYPE}", method.GetReturnTypeAsString());
		FindAndReplace(emitString, "{PARENT_QUALIFIED_NAME}", a_parentType.GetQualifiedName());
		FindAndReplace(emitString, "{PARENT_TYPENAME_AS_VAR}", GetTypeNameAsVar(a_parentType.GetQualifiedName()));
		FindAndReplace(emitString, "{ACCESS_SPECIFIER}", std::to_string(method.GetAccessSpecifier()));
		FindAndReplace(emitString, "{IS_CONST}", method.IsConst() ? "true" : "false");
		FindAndReplace(emitString, "{IS_VIRTUAL}", method.IsVirtual() ? "true" : "false");
		FindAndReplace(emitString, "{INVOKABLE_PTR}", method.GetArguments().size() != 0 ? "auto InvokablePtr = " : "");
		FindAndReplace(emitString, "{FN_CONST_QUAL}", method.IsConst() ? " const" : "");

		std::stringstream argSignature;
		for (size_t i = 0; i < method.GetArguments().size(); i++)
		{
			const auto& arg = method.GetArguments()[i];
			argSignature << arg.GetTypeAsString();

			if (i < method.GetArguments().size() - 1)
				argSignature << ", ";
		}

		FindAndReplace(emitString, "{ARG_SIGNATURE}", argSignature.str());

		std::stringstream rawAddress;
		if (method.IsDeleted())
		{
			rawAddress << "nullptr";
		} else if (method.GetAccessSpecifier() == Spyll::AccessSpecifier::Public)
		{
			// Namespace::Function
			rawAddress << "&" << method.GetQualifiedName();
		} else
		{
			// (Oyl::Reflection::Internal::StolenMember<__Stolen_Namespace_Function>::value)
			rawAddress << StolenMember(method);
		}
		FindAndReplace(emitString, "{RAW_FN_ADDRESS}", rawAddress.str());

		std::string typesafePtrString = GetTrimmedStringView(R"""(
auto thunkLambda = [](std::any& __a_self{NAME_SIGNATURE}) -> std::any
{
{RAW_CALL}
};
std::any(*thunkFnPtr)(std::any&{TYPE_SIGNATURE}) = thunkLambda;
MethodParams.typeSafeThunkFnPtr = reinterpret_cast<void*>(thunkFnPtr);
)"""
		).data();

		std::stringstream nameSignature;
		std::stringstream typeSignature;
		const auto& args = method.GetArguments();
		for (size_t i = 0; i < args.size(); i++)
		{
			typeSignature << ", ";
			nameSignature << ", ";

			const auto& arg = args[i];
			std::string_view std_any_ref = "std::any&";
			typeSignature << std_any_ref;
			nameSignature << std_any_ref << " " << arg.GetName();
		}
		FindAndReplace(typesafePtrString, "{NAME_SIGNATURE}", nameSignature.str());
		FindAndReplace(typesafePtrString, "{TYPE_SIGNATURE}", typeSignature.str());

		if (!method.IsDeleted())
		{
			std::stringstream callStatement;
			{
				std::string callFunc;
				if (method.GetAccessSpecifier() == Spyll::AccessSpecifier::Public)
				{
					// Namespace::Function
					callFunc = method.GetName();
				} else
				{
					// *(Oyl::Reflection::Internal::StolenMember<__Stolen_Namespace_Function>::value)
					callFunc = "*" + StolenMember(method);
				}
				callStatement << "(__self->" << callFunc << ")";
			}
			callStatement << "(" << (args.size() != 0 ? "\n" : "");
			for (size_t i = 0; i < args.size(); i++)
			{
				const auto& arg = args[i];

				std::string declaration = "\tstd::any_cast<{TYPE}>({NAME})";
				FindAndReplace(declaration, "{TYPE}", arg.GetTypeAsString());
				FindAndReplace(declaration, "{NAME}", arg.GetName());

				callStatement << declaration;
				if (i != args.size() - 1)
					callStatement << ", ";
				callStatement << "\n";
			}
			callStatement << ")";

			std::stringstream callReturn;
			callReturn << "auto __self = std::any_cast<" << a_parentType.GetQualifiedName() << "*>(__a_self);\n";
			if (method.GetReturnTypeAsString() == "void")
			{
				callReturn << callStatement.str() << ";\n";
				callReturn << "return std::any {};";
			} else
			{
				callReturn << "std::any result = " << callStatement.str() << ";\n";
				callReturn << "return result;";
			}
			AddIndentToStringStream(callReturn);
			FindAndReplace(typesafePtrString, "{RAW_CALL}", callReturn.str());
		} else
		{
			FindAndReplace(typesafePtrString, "{RAW_CALL}", "\treturn std::any {};");
		}

		std::stringstream typesafePtr;
		typesafePtr << typesafePtrString;
		AddIndentToStringStream(typesafePtr);
		FindAndReplace(emitString, "{TYPESAFE_PTR}", typesafePtr.str());

		std::stringstream argumentsStream;
		RegisterArgumentForFunction(argumentsStream, method);
		AddIndentToStringStream(argumentsStream);
		FindAndReplace(emitString, "{ARGUMENTS}", argumentsStream.str());

		a_stream << emitString;
	}
}

void
RegisterArgumentForFunction(
	std::stringstream& a_stream,
	const Spyll::Function& a_function
)
{
	for (const auto& arg : a_function.GetArguments())
	{
		std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::ArgumentParams ArgumentParams;
	ArgumentParams.type = Oyl::Reflection::Type::Get<{TYPE}>();
	ArgumentParams.name = "{NAME}";
	Oyl::Reflection::Internal::ReflectionFactory::AddArgumentToInvokable({INVOKABLE_PTR}, ArgumentParams, a_allocate);
}
)"""
		).data();

		FindAndReplace(emitString, "{TYPE}", arg.GetTypeAsString());
		FindAndReplace(emitString, "{NAME}", arg.GetName());
		FindAndReplace(emitString, "{INVOKABLE_PTR}", "InvokablePtr");

		a_stream << emitString;
	}
}

void
RegisterGlobalVariables(std::stringstream& a_stream, const Spyll::ReflectionParser* a_parser)
{
	(void) a_stream;
	(void) a_parser;

	for (const auto& variable : a_parser->GetGlobalVariables())
	{
		if (!variable.ShouldReflect())
			continue;

		std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::VariableParams VariableParams;
	VariableParams.qualifiedName = "{QUALIFIED_NAME}";
	VariableParams.name = "{NAME}";
	VariableParams.type = Oyl::Reflection::Type::Get<{QUALIFIED_TYPE}>();
	VariableParams.parentType = nullptr;
	VariableParams.accessSpecifier = Oyl::Reflection::AccessSpecifier::Global;
	Oyl::Reflection::Internal::ReflectionFactory::AddGlobalVariableToAssembly({ASSEMBLY_PTR}, VariableParams, a_allocate);
}
)"""
		).data();

		FindAndReplace(emitString, "{QUALIFIED_NAME}", variable.GetQualifiedName());
		FindAndReplace(emitString, "{NAME}", variable.GetName());
		FindAndReplace(emitString, "{QUALIFIED_TYPE}", variable.GetTypeAsString());
		FindAndReplace(emitString, "{ASSEMBLY_PTR}", "AssemblyPtr");

		a_stream << emitString;
	}
}

void
RegisterGlobalFunctions(std::stringstream& a_stream, const Spyll::ReflectionParser* a_parser)
{
	for (const auto& function : a_parser->GetGlobalFunctions())
	{
		if (!function.ShouldReflect())
			continue;

		std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::FunctionParams FunctionParams;
	FunctionParams.qualifiedName = "{QUALIFIED_NAME}";
	FunctionParams.name = "{NAME}";
	FunctionParams.returnType = Oyl::Reflection::Type::Get<{RETURN_TYPE}>();
	FunctionParams.parentType = nullptr;
	FunctionParams.accessSpecifier = Oyl::Reflection::AccessSpecifier::Global;
	{RETURN_TYPE}(*address)({ARG_SIGNATURE}) = {RAW_FN_ADDRESS};
	FunctionParams.rawFnPtr = reinterpret_cast<void*>(address);
{TYPESAFE_PTR}
	{INVOKABLE_PTR}Oyl::Reflection::Internal::ReflectionFactory::AddGlobalFunctionToAssembly({ASSEMBLY_PTR}, FunctionParams, a_allocate);
{ARGUMENTS}
}
)"""
		).data();

		FindAndReplace(emitString, "{QUALIFIED_NAME}", function.GetQualifiedName());
		FindAndReplace(emitString, "{NAME}", function.GetName());
		FindAndReplace(emitString, "{RETURN_TYPE}", function.GetReturnTypeAsString());
		FindAndReplace(emitString, "{INVOKABLE_PTR}", function.GetArguments().size() != 0 ? "auto InvokablePtr = " : "");
		FindAndReplace(emitString, "{ASSEMBLY_PTR}", "AssemblyPtr");
		FindAndReplace(emitString, "{RAW_FN_ADDRESS}", function.IsDeleted() ? "nullptr" : function.GetQualifiedName());

		std::stringstream argSignature;
		for (size_t i = 0; i < function.GetArguments().size(); i++)
		{
			const auto& arg = function.GetArguments()[i];
			argSignature << arg.GetTypeAsString();

			if (i < function.GetArguments().size() - 1)
				argSignature << ", ";
		}

		FindAndReplace(emitString, "{ARG_SIGNATURE}", argSignature.str());

		std::string typesafePtrString = GetTrimmedStringView(R"""(
auto thunkLambda = []({NAME_SIGNATURE}) -> std::any
{
{RAW_CALL}
};
std::any(*thunkFnPtr)({TYPE_SIGNATURE}) = thunkLambda;
FunctionParams.typeSafeThunkFnPtr = reinterpret_cast<void*>(thunkFnPtr);
)"""
		).data();

		std::stringstream nameSignature;
		std::stringstream typeSignature;
		const auto& args = function.GetArguments();
		for (size_t i = 0; i < args.size(); i++)
		{
			const auto& arg = args[i];
			std::string_view std_any_ref = "std::any&";
			typeSignature << std_any_ref;
			nameSignature << std_any_ref << " " << arg.GetName();

			if (i != args.size() - 1)
			{
				typeSignature << ", ";
				nameSignature << ", ";
			}
		}
		FindAndReplace(typesafePtrString, "{NAME_SIGNATURE}", nameSignature.str());
		FindAndReplace(typesafePtrString, "{TYPE_SIGNATURE}", typeSignature.str());

		if (!function.IsDeleted())
		{
			std::stringstream callStatement;
			callStatement << function.GetQualifiedName();
			callStatement << "(" << (args.size() != 0 ? "\n" : "");
			for (size_t i = 0; i < args.size(); i++)
			{
				const auto& arg = args[i];

				std::string declaration = "\tstd::any_cast<{TYPE}>({NAME})";
				FindAndReplace(declaration, "{TYPE}", arg.GetTypeAsString());
				FindAndReplace(declaration, "{NAME}", arg.GetName());

				callStatement << declaration;
				if (i != args.size() - 1)
					callStatement << ", ";
				callStatement << "\n";
			}
			callStatement << ")";

			std::stringstream callReturn;
			if (function.GetReturnTypeAsString() == "void")
			{
				callReturn << callStatement.str() << ";\n";
				callReturn << "return std::any {};";
			} else
			{
				callReturn << "std::any result = " << callStatement.str() << ";\n";
				callReturn << "return result;";
			}
			AddIndentToStringStream(callReturn);
			FindAndReplace(typesafePtrString, "{RAW_CALL}", callReturn.str());
		} else
		{
			FindAndReplace(typesafePtrString, "{RAW_CALL}", "\tstd::any {};");
		}

		std::stringstream typesafePtr;
		typesafePtr << typesafePtrString;
		AddIndentToStringStream(typesafePtr);
		FindAndReplace(emitString, "{TYPESAFE_PTR}", typesafePtr.str());

		std::stringstream argumentsStream;
		RegisterArgumentForFunction(argumentsStream, function);
		AddIndentToStringStream(argumentsStream);
		FindAndReplace(emitString, "{ARGUMENTS}", argumentsStream.str());

		a_stream << emitString;
	}
}

void
RegisterEnums(std::stringstream& a_stream, const Spyll::ReflectionParser* a_parser)
{
	for (const auto& enum_ : a_parser->GetEnums())
	{
		if (!enum_.ShouldReflect())
			continue;

		std::string emitString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::EnumParams EnumParams;
	EnumParams.qualifiedName = "{QUALIFIED_NAME}";
	EnumParams.name = "{NAME}";
	EnumParams.underlyingType = Oyl::Reflection::Type::Get<{UNDERLYING_TYPE}>();
	EnumParams.nValues = static_cast<size_t>({SIZE});
	{ENUM_PTR}Oyl::Reflection::Internal::ReflectionFactory::AddEnumToAssembly({ASSEMBLY_PTR}, EnumParams, a_allocate);
{ENTRIES}
}
)"""
		).data();

		FindAndReplace(emitString, "{QUALIFIED_NAME}", enum_.GetQualifiedName());
		FindAndReplace(emitString, "{NAME}", enum_.GetName());
		FindAndReplace(emitString, "{UNDERLYING_TYPE}", enum_.GetUnderlyingTypeAsString());
		FindAndReplace(emitString, "{SIZE}", std::to_string(enum_.GetEntries().size()));
		FindAndReplace(emitString, "{ASSEMBLY_PTR}", "AssemblyPtr");
		FindAndReplace(emitString, "{ENUM_PTR}", !enum_.GetEntries().empty() ? "auto EnumPtr = " : "");

		std::stringstream entryStream;
		for (const auto& entry : enum_.GetEntries())
		{
			std::string entryString = GetTrimmedStringView(R"""(
{
	Oyl::Reflection::Internal::EnumValueParams EnumValueParams;
	EnumValueParams.identifier = "{IDENTIFIER}";
	EnumValueParams.value = static_cast<{UNDERLYING_TYPE}>({VALUE});
	Oyl::Reflection::Internal::ReflectionFactory::AddValueToEnum(EnumPtr, EnumValueParams, a_allocate);
}
)"""
			).data();

			FindAndReplace(entryString, "{IDENTIFIER}", entry.GetIdentifier());
			FindAndReplace(entryString, "{VALUE}", std::to_string(entry.GetValue()));
			FindAndReplace(entryString, "{UNDERLYING_TYPE}", enum_.GetUnderlyingTypeAsString());

			entryStream << entryString;
		}

		AddIndentToStringStream(entryStream);
		FindAndReplace(emitString, "{ENTRIES}", entryStream.str());

		a_stream << emitString;
	}
}
