local Config = require "Config"

premake.modules.Clean = {}
local m = premake.modules.Clean

newoption {
    trigger     = "packages",
    description = "Compatible with 'clean' action. Cleans the package cache.",
    category    = "clean"
}

local cleanPackages = false

newaction {
    trigger = "clean",
    description = "Deletes the build directory and all project files",

    onStart = function()
        cleanPackages = _OPTIONS['packages'] ~= nil
    end,
    onWorkspace = function(wks) -- Keep onWorkspace to display completion time at the end
    end,
    execute = function()
        if os.isdir("Build") then
            print("Removing Build Directory...")
            os.rmdir("Build")
        end
        
        local filesToRemove = table.join(
            os.matchfiles("**.sln"),
            os.matchfiles("**.vcxproj*")
        )

        for _, file in pairs(filesToRemove) do
            -- Don't remove projects that aren't generated by us
            -- Current impl is to not remove projects below the root folder of packages
            -- TODO: Maintain list in file of generated files, read from this to clean
            local parentDir = path.getdirectory(file)
            local parentParentDir = path.getdirectory(parentDir)
            if not string.contains(parentDir, Config.PackagesDir) and
               not string.contains(parentParentDir, Config.PackagesDir) then
                print("Removing " .. file .. "...")
                os.remove(file)
            end
        end

        if cleanPackages then
            local packagesToRemove = os.matchdirs(Config.PackagesDir .. "*")
            for _, package in pairs(packagesToRemove) do
                print("Removing Package '" .. path.getbasename(package) .. "'...")
                os.rmdir(package)
            end
        end
    end,
}

return m