#include "Emit.h"

#include <filesystem>
#include <fstream>
#include <sstream>

#include "SpyllTool.h"

void
FindAndReplace(std::string& a_str, std::string_view a_find, std::string_view a_replace)
{
	size_t start_pos = 0;
	while ((start_pos = a_str.find(a_find, start_pos)) != std::string::npos)
	{
		a_str.replace(start_pos, a_find.length(), a_replace);
		start_pos += a_find.length(); // Handles case where 'to' is a substring of 'from'
	}
};

std::string
GetTypeNameAsVar(std::string_view a_name)
{
	std::string typeVar = std::string(a_name);
	std::replace(typeVar.begin(), typeVar.end(), ' ', '_');
	std::replace(typeVar.begin(), typeVar.end(), '-', '_');
	std::replace(typeVar.begin(), typeVar.end(), '.', '_');
	std::replace(typeVar.begin(), typeVar.end(), '<', '_');
	std::replace(typeVar.begin(), typeVar.end(), '>', '_');
	std::replace(typeVar.begin(), typeVar.end(), ',', '_');
	FindAndReplace(typeVar, "::", "_");
	FindAndReplace(typeVar, "*", "ptr_");
	typeVar += "Type";

	return typeVar;
}

void
EmitCodeFromTool(const Oyl::SpyllTool& a_tool)
{
	auto descriptor = a_tool.GetMergedReflectionDescriptor();

	std::filesystem::create_directory("Generated");

	std::ofstream generatedIncludeFile;
	generatedIncludeFile.open("Generated/Spyll.generated.cpp");

	std::string emitOutputTemplate = R"""(
{HEADER_COMMENT}

#include <Core/Reflection/ReflectionFactory.h>

{REFLECT_INCLUDES}

extern "C"
_OYL_EXPORT
void
ReflectionAssembly_Dependencies(int* a_count, const char** a_dependencies)
{
	*a_count = {DEPENDENCY_COUNT};

	{DEPENDENCIES}
	*a_dependencies = *dependencies;
}

extern "C"
_OYL_EXPORT
::Oyl::Reflection::Assembly*
ReflectionAssembly_Register(::Oyl::Reflection::Internal::ReflectionAllocatorFn a_allocate)
{
	Oyl::Reflection::Internal::AssemblyParams AssemblyParams;
	AssemblyParams.name = "{ASSEMBLY_NAME}";
	Oyl::Reflection::Assembly* AssemblyPtr = Oyl::Reflection::Internal::ReflectionFactory::CreateAssembly(AssemblyParams, a_allocate);

	//{EXISTING_TYPE_CACHE}

	{REGISTER}

	return AssemblyPtr;
}
)""";

	FindAndReplace(emitOutputTemplate, "{HEADER_COMMENT}", R"(
// Auto-Generated Source File, Generated by Oyl.Spyll
// {GENERATION_DATE}
// DO NOT MODIFY!
)");

	std::stringstream includes;
	for (const auto& type : descriptor.types)
	{
		if (type.isOpaque || type.sourceFile.empty())
		{
			continue;
		}

		includes << "#include \"" << type.sourceFile << "\"\n";
	}

	FindAndReplace(emitOutputTemplate, "{REFLECT_INCLUDES}", includes.str());

	std::stringstream dependenciesString;
	if (a_tool.dependencies.empty())
	{
		dependenciesString << "static const char** dependencies = nullptr";
	} else
	{
		dependenciesString << "static const char* dependencies[] = { ";
		for (const auto& dependency : a_tool.dependencies)
		{
			dependenciesString << dependency << ",";
		}		
		dependenciesString << " }";
	}
	dependenciesString << ";\n";

	FindAndReplace(emitOutputTemplate, "{DEPENDENCIES}", dependenciesString.str());
	FindAndReplace(emitOutputTemplate, "{DEPENDENCY_COUNT}", std::to_string(a_tool.dependencies.size()));

	std::stringstream registerStream;
	registerStream.setf(std::ios_base::boolalpha);
	for (const auto& type : descriptor.types)
	{
		if (type.isOpaque)
		{
			continue;
		}

		std::string typeVar = GetTypeNameAsVar(type.name);

		registerStream << "\tOyl::Reflection::Type* " << typeVar << ";\n";
		registerStream << "\t{\n";
		registerStream << "\t\tOyl::Reflection::Internal::TypeParams TypeParams;\n";
		registerStream << "\t\tTypeParams.assembly = AssemblyPtr;\n";
		registerStream << "\t\tTypeParams.typeId = Oyl::Reflection::GetTypeId<" << type.name << ">();\n";
		registerStream << "\t\tTypeParams.qualifiedName = \"" << type.name << "\";\n";
		registerStream << "\t\tTypeParams.name = TypeParams.qualifiedName.substr(" << type.name.rfind("::") + 2 << ");\n";
		registerStream << "\t\tTypeParams.size = " << (type.sizeInBits / 8) << ";\n";
		registerStream << "\t\tTypeParams.alignment = " << (uint32_t) type.alignment << ";\n";
		registerStream << "\t\tTypeParams.isComposite = " << type.isComposite << ";\n";
		registerStream << "\t\tTypeParams.isStruct = " << type.isStruct << ";\n";
		registerStream << "\t\tTypeParams.isOpaque = " << type.isOpaque << ";\n";
		registerStream << "\t\t" << typeVar << " = Oyl::Reflection::Internal::ReflectionFactory::AddTypeToAssembly(AssemblyPtr, TypeParams, a_allocate);\n";
		registerStream << "\t}\n";
	}

	for (const auto& field : descriptor.fields)
	{
		const auto& type = descriptor.types[(size_t) field.type];
		const auto& ownerType = descriptor.types[(size_t) field.ownerType];

		auto ownerTypeVar = GetTypeNameAsVar(ownerType.name);

		registerStream << "\t{\n";
		registerStream << "\t\tOyl::Reflection::Internal::FieldParams FieldParams;\n";
		registerStream << "\t\tFieldParams.qualifiedName = \"" << ownerType.name << "::" << field.name << "\";\n";
		registerStream << "\t\tFieldParams.name = FieldParams.qualifiedName.substr(" << ownerType.name.size() + 2 << ");\n";
		registerStream << "\t\tFieldParams.type = Oyl::Reflection::Type::Get<" << type.name << ">();\n";
		registerStream << "\t\tFieldParams.ownerType = " << ownerTypeVar << ";\n";
		registerStream << "\t\tFieldParams.offsetInBits = " << field.offsetInBits << ";\n";
		registerStream << "\t\tFieldParams.accessSpecifier = (Oyl::Reflection::AccessSpecifier) (" << (uint32_t) field.accessSpecifier << ");\n";
		registerStream << "\t\tFieldParams.isConst = " << field.isConst << ";\n";
		registerStream << "\t\tFieldParams.isVolatile = " << field.isVolatile << ";\n";
		registerStream << "\t\tFieldParams.isReference = " << field.isReference << ";\n";
		registerStream << "\t\tFieldParams.isPointer = " << field.isPointer << ";\n";
		registerStream << "\t\tOyl::Reflection::Internal::ReflectionFactory::AddFieldToType(" << ownerTypeVar << ", FieldParams, a_allocate);\n";
		registerStream << "\t}\n";
	}

	for (const auto& function : descriptor.functions)
	{
		if (function.ownerType == Spyll::TypeDescriptorId::Invalid)
		{
			continue;
		}

		const auto& returnType = descriptor.types[(size_t) function.returnType];
		const auto& ownerType = descriptor.types[(size_t) function.ownerType];

		auto ownerTypeVar = GetTypeNameAsVar(ownerType.name);

		registerStream << "\t{\n";
		registerStream << "\t\tOyl::Reflection::Internal::MemberFunctionParams FunctionParams;\n";
		registerStream << "\t\tFunctionParams.qualifiedName = \"" << ownerType.name << "::" << function.name << "\";\n";
		registerStream << "\t\tFunctionParams.name = FunctionParams.qualifiedName.substr(" << ownerType.name.size() + 2 << ");\n";
		registerStream << "\t\tFunctionParams.returnType = Oyl::Reflection::Type::Get<" << returnType.name << ">();\n";
		registerStream << "\t\tFunctionParams.ownerType = " << ownerTypeVar << ";\n";
		registerStream << "\t\tFunctionParams.accessSpecifier = (Oyl::Reflection::AccessSpecifier) (" << (uint32_t) function.accessSpecifier << ");\n";
		registerStream << "\t\tFunctionParams.constructorType = (Oyl::Reflection::ConstructorType) (" << (uint32_t) function.constructorType << ");\n";
		registerStream << "\t\tFunctionParams.isVirtual = " << function.isVirtual << ";\n";
		registerStream << "\t\tFunctionParams.isPureVirtual = " << function.isPureVirtual << ";\n";
		registerStream << "\t\tFunctionParams.isOverride = " << function.isOverride << ";\n";
		registerStream << "\t\tFunctionParams.isStatic = " << function.isStatic << ";\n";
		registerStream << "\t\tFunctionParams.isConst = " << function.isConst << ";\n";
		registerStream << "\t\tFunctionParams.isVolatile = " << function.isVolatile << ";\n";
		registerStream << "\t\tFunctionParams.isReturnConst = " << function.isReturnConst << ";\n";
		registerStream << "\t\tFunctionParams.isReturnVolatile = " << function.isReturnVolatile << ";\n";
		registerStream << "\t\tFunctionParams.isReturnReference = " << function.isReturnReference << ";\n";
		registerStream << "\t\tFunctionParams.isReturnPointer = " << function.isReturnPointer << ";\n";
		registerStream << "\t\tOyl::Reflection::Internal::ReflectionFactory::AddFunctionToType(" << ownerTypeVar << ", FunctionParams, a_allocate);\n";
		registerStream << "\t}\n";
	}

	FindAndReplace(emitOutputTemplate, "{REGISTER}", registerStream.str());

	FindAndReplace(emitOutputTemplate, "{ASSEMBLY_NAME}", a_tool.assemblyName);

	generatedIncludeFile << emitOutputTemplate;
}
