#include "Emit.h"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <unordered_set>

#include <Spyll/Tool/Core/ReflectionParser.h>

#include "SpyllTool.h"

void
FindAndReplace(std::string& a_str, std::string_view a_find, std::string_view a_replace)
{
	size_t start_pos = 0;
	while ((start_pos = a_str.find(a_find, start_pos)) != std::string::npos)
	{
		a_str.replace(start_pos, a_find.length(), a_replace);
		start_pos += a_find.length(); // Handles case where 'to' is a substring of 'from'
	}
};

std::string
GetTypeNameAsVar(std::string_view a_name)
{
	std::string typeVar = std::string(a_name);
	std::replace(typeVar.begin(), typeVar.end(), ' ', '_');
	std::replace(typeVar.begin(), typeVar.end(), '-', '_');
	std::replace(typeVar.begin(), typeVar.end(), '.', '_');
	std::replace(typeVar.begin(), typeVar.end(), '<', '_');
	std::replace(typeVar.begin(), typeVar.end(), '>', '_');
	std::replace(typeVar.begin(), typeVar.end(), ',', '_');
	FindAndReplace(typeVar, "::", "_");
	FindAndReplace(typeVar, "*", "ptr_");
	typeVar += "Type";

	return typeVar;
}

static constexpr
std::string_view g_emitTemplate =
	R"""(
{HEADER_COMMENT}

#include <Core/Reflection/ReflectionFactory.h>

{REFLECT_INCLUDES}

extern "C"
_OYL_EXPORT
void
_ReflectionAssembly_Dependencies(int* a_count, const char** a_dependencies)
{
	*a_count = {DEPENDENCY_COUNT};

	{DEPENDENCIES}
	*a_dependencies = *dependencies;
}

extern "C"
_OYL_EXPORT
::Oyl::Reflection::Assembly*
_ReflectionAssembly_Register(::Oyl::Reflection::Internal::ReflectionAllocatorFn a_allocate)
{
	Oyl::Reflection::Internal::AssemblyParams AssemblyParams;
	AssemblyParams.name = "{ASSEMBLY_NAME}";
	Oyl::Reflection::Assembly* AssemblyPtr = Oyl::Reflection::Internal::ReflectionFactory::CreateAssembly(AssemblyParams, a_allocate);

	{REFLECTION_REGISTER}

	return AssemblyPtr;
}
)""";

void
EmitHeaderComment(std::string& a_emitString);

void
EmitIncludes(std::string& a_emitString, const Spyll::ReflectionParser* a_parser);

void
EmitDependencies(std::string& a_emitString, const std::vector<std::string_view>& a_tool);

void
PushIndent(std::string& a_indent);

void
PopIndent(std::string& a_indent);

void
EmitReflectionRegister(std::string& a_emitString, const Spyll::ReflectionParser* a_parser);

void
RegisterTypes(std::stringstream& a_stream, std::string& a_indent, const Spyll::ReflectionParser* a_parser);

void
RegisterVariablesForType(
	std::stringstream& a_stream,
	std::string& a_indent,
	const Spyll::Type* a_ownerType
);

void
RegisterFieldsForType(
	std::stringstream& a_stream,
	std::string& a_indent,
	const Spyll::Type* a_ownerType
);

void
RegisterFunctionsForType(
	std::stringstream& a_stream,
	std::string& a_indent,
	const Spyll::Type* a_ownerType
);

void
RegisterMethodsForType(
	std::stringstream& a_stream,
	std::string& a_indent,
	const Spyll::Type* a_ownerType
);

void
RegisterArgumentForFunction(
	std::stringstream& a_stream,
	std::string& a_indent,
	const Spyll::Function* a_function
);

void
RegisterGlobalVariables(
	std::stringstream& a_stream,
	std::string& a_indent,
	const Spyll::ReflectionParser* a_parser
);

void
RegisterGlobalFunctions(
	std::stringstream& a_stream,
	std::string& a_indent,
	const Spyll::ReflectionParser* a_parser
);

void
RegisterEnums(
	std::stringstream& a_stream,
	std::string& a_indent,
	const Spyll::ReflectionParser* a_parser
);

void
EmitCodeFromTool(const Spyll::ReflectionParser* a_parser)
{
	std::filesystem::create_directory("Generated");

	std::ofstream generatedIncludeFile;
	generatedIncludeFile.open("Generated/Spyll.generated.cpp");

	std::string emitString = std::string(g_emitTemplate);

	EmitHeaderComment(emitString);
	EmitIncludes(emitString, a_parser);
	EmitDependencies(emitString, g_tool.dependencies);
	EmitReflectionRegister(emitString, a_parser);

	FindAndReplace(emitString, "{ASSEMBLY_NAME}", g_tool.assemblyName);

	generatedIncludeFile << emitString;
}

void
EmitHeaderComment(std::string& a_emitString)
{
	std::string_view result =
		"// Auto-Generated Source File, Generated by Oyl.Spyll\n"
		"// {GENERATION_DATE}\n"
		"// DO NOT MODIFY!\n";

	FindAndReplace(a_emitString, "{HEADER_COMMENT}", result);
}

void
EmitIncludes(std::string& a_emitString, const Spyll::ReflectionParser* a_parser)
{
	std::unordered_set<std::string_view> includeSet;

	for (const Spyll::Type* type : a_parser->GetTypes())
	{
		includeSet.insert(type->GetSourceFile());
	}

	for (const Spyll::Variable* variable : a_parser->GetGlobalVariables())
	{
		includeSet.insert(variable->GetSourceFile());
	}

	for (const Spyll::Function* function : a_parser->GetGlobalFunctions())
	{
		includeSet.insert(function->GetSourceFile());
	}

	for (const Spyll::Enum* enum_ : a_parser->GetEnums())
	{
		includeSet.insert(enum_->GetSourceFile());
	}

	std::stringstream includes;
	for (const auto& include : includeSet)
	{
		includes << "#include <" << include << ">\n";
	}
	FindAndReplace(a_emitString, "{REFLECT_INCLUDES}", includes.str());
}

void
EmitDependencies(std::string& a_emitString, const std::vector<std::string_view>& a_dependencies)
{
	std::stringstream dependenciesListString;
	if (a_dependencies.empty())
	{
		dependenciesListString << "static const char** dependencies = nullptr";
	} else
	{
		dependenciesListString << "static const char* dependencies[] = { ";
		for (const auto& dependency : a_dependencies)
		{
			dependenciesListString << dependency << ",";
		}
		dependenciesListString << " }";
	}
	dependenciesListString << ";\n";

	FindAndReplace(a_emitString, "{DEPENDENCIES}", dependenciesListString.str());
	FindAndReplace(a_emitString, "{DEPENDENCY_COUNT}", std::to_string(a_dependencies.size()));
}

void
PushIndent(std::string& a_indent)
{
	a_indent += "\t";
}

void
PopIndent(std::string& a_indent)
{
	a_indent = a_indent.substr(0, a_indent.size() - 1);
}

void
EmitReflectionRegister(std::string& a_emitString, const Spyll::ReflectionParser* a_parser)
{
	std::stringstream stream;
	stream.setf(std::ios::boolalpha);
	stream << "\n";

	std::string indent = "\t";

	RegisterTypes(stream, indent, a_parser);
	RegisterGlobalVariables(stream, indent, a_parser);
	RegisterGlobalFunctions(stream, indent, a_parser);
	RegisterEnums(stream, indent, a_parser);

	FindAndReplace(a_emitString, "{REFLECTION_REGISTER}", stream.str());
}

void
RegisterTypes(std::stringstream& a_stream, std::string& a_indent, const Spyll::ReflectionParser* a_parser)
{
	for (const auto& type : a_parser->GetTypes())
	{
		std::string typeVar = GetTypeNameAsVar(type->GetQualifiedName());

		a_stream << a_indent << "Oyl::Reflection::Type* " << typeVar << ";\n";
		a_stream << a_indent << "{\n";
		a_stream << a_indent << "\tOyl::Reflection::Internal::TypeParams TypeParams;\n";
		a_stream << a_indent << "\tTypeParams.assembly = AssemblyPtr;\n";
		a_stream << a_indent << "\tTypeParams.typeId = Oyl::Reflection::GetTypeId<" << type->GetQualifiedName() <<
			">();\n";
		a_stream << a_indent << "\tTypeParams.qualifiedName = \"" << type->GetQualifiedName() << "\";\n";
		a_stream << a_indent << "\tTypeParams.name = \"" << type->GetName() << "\";\n";
		a_stream << a_indent << "\tTypeParams.size = " << type->GetSize() << ";\n";
		a_stream << a_indent << "\tTypeParams.alignment = " << static_cast<uint32_t>(type->GetAlignment()) << ";\n";
		a_stream << a_indent << "\t" << typeVar <<
			" = Oyl::Reflection::Internal::ReflectionFactory::AddTypeToAssembly(AssemblyPtr, TypeParams, a_allocate);\n";

		PushIndent(a_indent);
		{
			RegisterVariablesForType(a_stream, a_indent, type);
			RegisterFieldsForType(a_stream, a_indent, type);

			RegisterFunctionsForType(a_stream, a_indent, type);
			RegisterMethodsForType(a_stream, a_indent, type);
		}
		PopIndent(a_indent);

		a_stream << a_indent << "}\n";
	}
}

void
RegisterVariablesForType(
	std::stringstream& a_stream,
	std::string& a_indent,
	const Spyll::Type* a_ownerType
)
{
	for (const auto& variable : a_ownerType->GetVariables())
	{
		auto parentTypeVar = GetTypeNameAsVar(a_ownerType->GetQualifiedName());

		a_stream << a_indent << "{\n";
		a_stream << a_indent << "\tOyl::Reflection::Internal::VariableParams VariableParams;\n";
		a_stream << a_indent << "\tVariableParams.qualifiedName = \"" << variable.GetQualifiedName() << "\";\n";
		a_stream << a_indent << "\tVariableParams.name = \"" << variable.GetName() << "\";\n";
		a_stream << a_indent << "\tVariableParams.type = Oyl::Reflection::Type::Get<" << variable.GetTypeAsString() <<
			">();\n";
		a_stream << a_indent << "\tVariableParams.parentType = " << parentTypeVar << ";\n";
		a_stream << a_indent << "\tVariableParams.accessSpecifier = static_cast<Oyl::Reflection::AccessSpecifier>(" <<
			static_cast<uint32_t>(variable.GetAccessSpecifier()) << ");\n";
		a_stream << a_indent << "\tOyl::Reflection::Internal::ReflectionFactory::AddVariableToType(" << parentTypeVar <<
			", VariableParams, a_allocate);\n";
		a_stream << a_indent << "}\n";
	}
}

void
RegisterFieldsForType(
	std::stringstream& a_stream,
	std::string& a_indent,
	const Spyll::Type* a_ownerType
)
{
	for (const auto& field : a_ownerType->GetFields())
	{
		auto parentTypeVar = GetTypeNameAsVar(a_ownerType->GetQualifiedName());

		a_stream << a_indent << "{\n";
		a_stream << a_indent << "\tOyl::Reflection::Internal::FieldParams FieldParams;\n";
		a_stream << a_indent << "\tFieldParams.qualifiedName = \"" << field.GetQualifiedName() << "\";\n";
		a_stream << a_indent << "\tFieldParams.name = \"" << field.GetName() << "\";\n";
		a_stream << a_indent << "\tFieldParams.type = Oyl::Reflection::Type::Get<" << field.GetTypeAsString() <<
			">();\n";
		a_stream << a_indent << "\tFieldParams.parentType = " << parentTypeVar << ";\n";
		a_stream << a_indent << "\tFieldParams.offsetInBits = " << field.GetOffsetInBits() << ";\n";
		a_stream << a_indent << "\tFieldParams.accessSpecifier = static_cast<Oyl::Reflection::AccessSpecifier>(" <<
			static_cast<uint32_t>(field.GetAccessSpecifier()) << ");\n";
		a_stream << a_indent << "\tFieldParams.isConst = " << field.IsConst() << ";\n";
		a_stream << a_indent << "\tOyl::Reflection::Internal::ReflectionFactory::AddFieldToType(" << parentTypeVar <<
			", FieldParams, a_allocate);\n";
		a_stream << a_indent << "}\n";
	}
}

void
RegisterFunctionsForType(
	std::stringstream& a_stream,
	std::string& a_indent,
	const Spyll::Type* a_ownerType
)
{
	for (const auto& function : a_ownerType->GetFunctions())
	{
		auto parentTypeVar = GetTypeNameAsVar(a_ownerType->GetQualifiedName());

		a_stream << a_indent << "{\n";
		a_stream << a_indent << "\tOyl::Reflection::Internal::FunctionParams FunctionParams;\n";
		a_stream << a_indent << "\tFunctionParams.qualifiedName = \"" << function.GetQualifiedName() << "\";\n";
		a_stream << a_indent << "\tFunctionParams.name = \"" << function.GetName() << "\";\n";
		a_stream << a_indent << "\tFunctionParams.returnType = Oyl::Reflection::Type::Get<" << function.
			GetReturnTypeAsString() << ">();\n";
		a_stream << a_indent << "\tFunctionParams.parentType = " << parentTypeVar << ";\n";
		a_stream << a_indent << "\tFunctionParams.accessSpecifier = static_cast<Oyl::Reflection::AccessSpecifier>(" <<
			static_cast<uint32_t>(function.GetAccessSpecifier()) << ");\n";
		a_stream << a_indent << "\tFunctionParams.functionPtr = reinterpret_cast<void*>(" << function.GetQualifiedName() << ");\n";
		a_stream << a_indent << "\tauto InvokablePtr = Oyl::Reflection::Internal::ReflectionFactory::AddFunctionToType("
			<< parentTypeVar << ", FunctionParams, a_allocate);\n";

		PushIndent(a_indent);
		{
			RegisterArgumentForFunction(a_stream, a_indent, &function);
		}
		PopIndent(a_indent);

		a_stream << a_indent << "}\n";
	}
}

void
RegisterMethodsForType(
	std::stringstream& a_stream,
	std::string& a_indent,
	const Spyll::Type* a_ownerType
)
{
	for (const auto& method : a_ownerType->GetMethods())
	{
		auto parentTypeVar = GetTypeNameAsVar(a_ownerType->GetQualifiedName());

		a_stream << a_indent << "{\n";
		a_stream << a_indent << "\tOyl::Reflection::Internal::MethodParams FunctionParams;\n";
		a_stream << a_indent << "\tFunctionParams.qualifiedName = \"" << method.GetQualifiedName() << "\";\n";
		a_stream << a_indent << "\tFunctionParams.name = \"" << method.GetName() << "\";\n";
		a_stream << a_indent << "\tFunctionParams.returnType = Oyl::Reflection::Type::Get<" << method.
			GetReturnTypeAsString() << ">();\n";
		a_stream << a_indent << "\tFunctionParams.parentType = " << parentTypeVar << ";\n";
		a_stream << a_indent << "\tFunctionParams.accessSpecifier = static_cast<Oyl::Reflection::AccessSpecifier>(" <<
			static_cast<uint32_t>(method.GetAccessSpecifier()) << ");\n";
		a_stream << a_indent << "\tFunctionParams.isConst = " << method.IsConst() << ";\n";
		a_stream << a_indent << "\tFunctionParams.isVirtual = " << method.IsVirtual() << ";\n";
		a_stream << a_indent << "\tdecltype(&" << method.GetQualifiedName() << ") temp = &" << method.GetQualifiedName() << ";\n";
		a_stream << a_indent << "\tFunctionParams.functionPtr = *reinterpret_cast<void**>(&temp);\n";
		a_stream << a_indent << "\tauto InvokablePtr = Oyl::Reflection::Internal::ReflectionFactory::AddFunctionToType("
			<< parentTypeVar << ", FunctionParams, a_allocate);\n";

		PushIndent(a_indent);
		{
			RegisterArgumentForFunction(a_stream, a_indent, &method);
		}
		PopIndent(a_indent);

		a_stream << a_indent << "}\n";
	}
}

void
RegisterArgumentForFunction(
	std::stringstream& a_stream,
	std::string& a_indent,
	const Spyll::Function* a_function
)
{
	for (const auto& argument : a_function->GetArguments())
	{
		a_stream << a_indent << "{\n";
		a_stream << a_indent << "\tOyl::Reflection::Internal::ArgumentParams ArgumentParams;\n";
		a_stream << a_indent << "\tArgumentParams.type = Oyl::Reflection::Type::Get<" << argument.type << ">();\n";
		a_stream << a_indent << "\tArgumentParams.name = \"" << argument.name << "\";\n";
		a_stream << a_indent <<
			"\tOyl::Reflection::Internal::ReflectionFactory::AddArgumentToInvokable(InvokablePtr, ArgumentParams, a_allocate);\n";
		a_stream << a_indent << "}\n";
	}
}

void
RegisterGlobalVariables(std::stringstream& a_stream, std::string& a_indent, const Spyll::ReflectionParser* a_parser)
{
	for (const auto& variable : a_parser->GetGlobalVariables())
	{
		a_stream << a_indent << "{\n";
		a_stream << a_indent << "\tOyl::Reflection::Internal::VariableParams VariableParams;\n";
		a_stream << a_indent << "\tVariableParams.qualifiedName = \"" << variable->GetQualifiedName() << "\";\n";
		a_stream << a_indent << "\tVariableParams.name = \"" << variable->GetName() << "\";\n";
		a_stream << a_indent << "\tVariableParams.type = Oyl::Reflection::Type::Get<" << variable->GetTypeAsString() <<
			">();\n";
		a_stream << a_indent << "\tVariableParams.parentType = nullptr;\n";
		a_stream << a_indent << "\tVariableParams.accessSpecifier = static_cast<Oyl::Reflection::AccessSpecifier>(" <<
			static_cast<uint32_t>(variable->GetAccessSpecifier()) << ");\n";
		a_stream << a_indent <<
			"\tOyl::Reflection::Internal::ReflectionFactory::AddGlobalVariableToAssembly(AssemblyPtr, VariableParams, a_allocate);\n";
		a_stream << a_indent << "}\n";
	}
}

void
RegisterGlobalFunctions(std::stringstream& a_stream, std::string& a_indent, const Spyll::ReflectionParser* a_parser)
{
	for (const auto& function : a_parser->GetGlobalFunctions())
	{
		a_stream << a_indent << "{\n";
		a_stream << a_indent << "\tOyl::Reflection::Internal::FunctionParams FunctionParams;\n";
		a_stream << a_indent << "\tFunctionParams.qualifiedName = \"" << function->GetQualifiedName() << "\";\n";
		a_stream << a_indent << "\tFunctionParams.name = \"" << function->GetName() << "\";\n";
		a_stream << a_indent << "\tFunctionParams.returnType = Oyl::Reflection::Type::Get<" << function->GetReturnTypeAsString() << ">();\n";
		a_stream << a_indent << "\tFunctionParams.parentType = nullptr;\n";
		a_stream << a_indent << "\tFunctionParams.accessSpecifier = static_cast<Oyl::Reflection::AccessSpecifier>(" << static_cast<uint32_t>(function->GetAccessSpecifier()) << ");\n";
		a_stream << a_indent << "\tFunctionParams.functionPtr = reinterpret_cast<void*>(" << function->GetQualifiedName() << ");\n";
		a_stream << a_indent << "\tauto InvokablePtr = Oyl::Reflection::Internal::ReflectionFactory::AddGlobalFunctionToAssembly(AssemblyPtr, FunctionParams, a_allocate);\n";

		PushIndent(a_indent);
		{
			RegisterArgumentForFunction(a_stream, a_indent, function);
		}
		PopIndent(a_indent);

		a_stream << a_indent << "}\n";
	}
}

void
RegisterEnums(std::stringstream& a_stream, std::string& a_indent, const Spyll::ReflectionParser* a_parser)
{
	for (const auto& enum_ : a_parser->GetEnums())
	{
		a_stream << a_indent << "{\n";
		a_stream << a_indent << "\tOyl::Reflection::Internal::EnumParams EnumParams;\n";
		a_stream << a_indent << "\tEnumParams.qualifiedName = \"" << enum_->GetQualifiedName() << "\";\n";
		a_stream << a_indent << "\tEnumParams.name = \"" << enum_->GetName() << "\";\n";
		a_stream << a_indent << "\tEnumParams.underlyingType = Oyl::Reflection::Type::Get<" << enum_->
			GetUnderlyingTypeAsString() << ">();\n";
		a_stream << a_indent << "\tEnumParams.nValues = static_cast<size_t>(" << enum_->GetEntries().size() << ");\n";
		a_stream << a_indent <<
			"\tauto EnumPtr = Oyl::Reflection::Internal::ReflectionFactory::AddEnumToAssembly(AssemblyPtr, EnumParams, a_allocate);\n";

		for (auto& entry : enum_->GetEntries())
		{
			PushIndent(a_indent);
			{
				a_stream << a_indent << "{\n";
				a_stream << a_indent << "\tOyl::Reflection::Internal::EnumValueParams EnumValueParams;\n";
				a_stream << a_indent << "\tEnumValueParams.identifier = \"" << entry.identifier << "\";\n";
				a_stream << a_indent << "\tEnumValueParams.value = static_cast<" << enum_->GetUnderlyingTypeAsString()
					<< ">(" << entry.value << ");\n";
				a_stream << a_indent <<
					"\tOyl::Reflection::Internal::ReflectionFactory::AddValueToEnum(EnumPtr, EnumValueParams, a_allocate);\n";
				a_stream << a_indent << "}\n";
			}
			PopIndent(a_indent);
		}

		a_stream << a_indent << "}\n";
	}
}
